-- Wurm Iso: the whole island, in one go.
--
-- Generated by scripts/bundle-sql.mjs from supabase/migrations/. Do not edit:
-- run `npm run db:bundle` instead.
--
-- Paste the lot into the SQL editor in the Supabase dashboard and press Run.
-- Safe to run more than once: everything here is create-or-replace or
-- create-if-not-exists.


-- ======================================================================
-- 20260914180100_world.sql
-- ======================================================================

-- The island, and everybody on it.
--
-- ## Why the land is rows of bytes
--
-- An island is five arrays of a million-odd entries. A row per tile would be
-- a million rows and a hundred megabytes an island; a single blob would be six
-- megabytes rewritten every time somebody dug a hole, and — worse — opaque to
-- the database, which now has to *check* digs rather than take them on trust.
--
-- So the land is stored a world-row at a time: one row of the table per row of
-- the island, each holding that row's slice of each array as `bytea`. A dig
-- reads and writes two rows. Every slice is a few kilobytes, which is under
-- the size at which Postgres moves a value out of line, so reading one byte
-- costs one page rather than a detour through TOAST.
--
-- Corners and tiles are separate tables because there is one more corner than
-- there are tiles in each direction, and because keeping each row's total well
-- under that size limit is the whole point.

create extension if not exists pgcrypto;

create table if not exists world (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(name) between 1 and 40),
  seed bigint not null,
  size int not null check (size between 8 and 4096),
  spawn_x int not null,
  spawn_y int not null,
  /**
   * When the island began. The time of day is not stored and never ticks: it
   * is this, subtracted from the wall clock. Nothing has to advance it, no
   * two machines can disagree about it, and an island nobody has visited for a
   * week has had a week of nights — which is what everybody expected anyway.
   */
  epoch timestamptz not null default now(),
  /** Whether the land has finished being uploaded. Nobody may join before it has. */
  ready boolean not null default false,
  made_by uuid,
  made_at timestamptz not null default now()
);

create table if not exists land_corner (
  world_id uuid not null references world on delete cascade,
  y int not null,
  /** Heights, signed 16-bit little-endian, one per corner across: size + 1 of them. */
  heights bytea not null,
  /** How much soil is over the rock at each corner, one byte each. */
  dirt bytea not null,
  primary key (world_id, y)
);

create table if not exists land_tile (
  world_id uuid not null references world on delete cascade,
  y int not null,
  tiles bytea not null,
  data bytea not null,
  rock bytea not null,
  primary key (world_id, y)
);

create table if not exists player (
  world_id uuid not null references world on delete cascade,
  uid uuid not null,
  name text not null check (length(name) between 1 and 20),
  x double precision not null,
  y double precision not null,
  level int not null default 0,
  /**
   * Where the body is, as the island believes it. A client says where it has
   * walked to and the island checks the claim against the clock before
   * believing it, which is the only reason the timestamp is here.
   */
  moved_at timestamptz not null default now(),
  stats jsonb not null default '{}',
  nutrition jsonb not null default '{}',
  knacks jsonb not null default '{}',
  titles jsonb not null default '[]',
  wounds jsonb not null default '[]',
  equipped jsonb not null default '{}',
  belt jsonb not null default '[]',
  boons jsonb not null default '[]',
  favour real not null default 0,
  rested real not null default 0,
  way text,
  title text,
  /**
   * What they are in the middle of. The island decides when it finishes, and
   * nothing is running to notice: the work is settled the next time anything
   * touches this row, and by a slow sweep for anyone who has wandered off.
   */
  act text,
  act_target jsonb,
  act_started timestamptz,
  act_ends timestamptz,
  act_left int,
  seen_at timestamptz not null default now(),
  joined_at timestamptz not null default now(),
  primary key (world_id, uid)
);

create table if not exists skill (
  world_id uuid not null,
  uid uuid not null,
  id text not null,
  value real not null,
  primary key (world_id, uid, id),
  foreign key (world_id, uid) references player (world_id, uid) on delete cascade
);

/**
 * Every item on the island, and the well its numbers come from.
 *
 * `generated always as identity` is the uid well made honest: one sequence per
 * island's worth of items, handed out by the database, so two people reaching
 * for the same number at the same instant is not a thing that can happen.
 */
create table if not exists item (
  id bigint primary key generated always as identity,
  world_id uuid not null references world on delete cascade,
  /** Who or what is holding it: 'player', 'ground', 'crate', 'bag'. */
  holder text not null,
  holder_uid uuid,
  gx int,
  gy int,
  inside bigint references item (id) on delete cascade,
  def text not null,
  ql real not null check (ql between 0 and 100),
  dmg real not null default 0 check (dmg between 0 and 100),
  count int not null default 1 check (count > 0),
  extra text,
  rare text,
  dye text,
  bless real,
  charges int,
  locked boolean not null default false,
  issued boolean not null default false,
  made_at timestamptz not null default now()
);

create index if not exists item_by_holder on item (world_id, holder, holder_uid);
create index if not exists item_on_ground on item (world_id, gx, gy) where holder = 'ground';

/**
 * What has changed about the land since it was uploaded.
 *
 * Two jobs in one table: it is what Realtime carries to everybody looking at
 * the island, and it is how somebody who was away catches up without
 * downloading six megabytes again.
 */
create table if not exists tile_change (
  world_id uuid not null references world on delete cascade,
  n bigint generated always as identity,
  x int not null,
  y int not null,
  tile int not null,
  data int not null,
  corners int[] not null,
  at timestamptz not null default now(),
  primary key (world_id, n)
);

/** What somebody is told. One line, to one person, on one island. */
create table if not exists event (
  world_id uuid not null references world on delete cascade,
  n bigint generated always as identity,
  uid uuid,
  text text not null,
  kind text not null default 'event',
  at timestamptz not null default now(),
  primary key (world_id, n)
);

create index if not exists event_for_player on event (world_id, uid, n desc);

-- ======================================================================
-- 20260914180200_land.sql
-- ======================================================================

-- Reading and writing one corner or one tile of the land.
--
-- These are the only things that know the land is bytes. Everything above
-- asks for the height of a corner and is given a number, exactly as the
-- TypeScript world does, so the rules read the same in both places.

/** A signed 16-bit little-endian value out of a byte string. */
create or replace function b_i16(b bytea, i int) returns int language sql immutable as $$
  select case when v > 32767 then v - 65536 else v end
  from (select get_byte(b, i * 2) | (get_byte(b, i * 2 + 1) << 8) as v) q
$$;

/** And back in again. */
create or replace function b_put_i16(b bytea, i int, v int) returns bytea language sql immutable as $$
  select set_byte(set_byte(b, i * 2, (v & 255)), i * 2 + 1, ((v >> 8) & 255))
$$;

/**
 * Every accessor below takes `p_`-prefixed arguments, without exception.
 *
 * `land_tile` is both a table and a function, and when the function's argument
 * was plainly `y` the condition `y = land_tile.y` bound *both* sides to the
 * table's column: a where clause reading `y = y`, true of every row, returning
 * whichever row came first. It read plausible values from the wrong row of the
 * island and nothing complained. The prefix is not decoration.
 */
create or replace function land_height(p_world uuid, p_x int, p_y int) returns int language sql stable as $$
  select b_i16(c.heights, p_x) from land_corner c where c.world_id = p_world and c.y = p_y
$$;

create or replace function land_dirt(p_world uuid, p_x int, p_y int) returns int language sql stable as $$
  select get_byte(c.dirt, p_x) from land_corner c where c.world_id = p_world and c.y = p_y
$$;

create or replace function land_tile(p_world uuid, p_x int, p_y int) returns int language sql stable as $$
  select get_byte(t.tiles, p_x) from land_tile t where t.world_id = p_world and t.y = p_y
$$;

create or replace function land_data(p_world uuid, p_x int, p_y int) returns int language sql stable as $$
  select get_byte(t.data, p_x) from land_tile t where t.world_id = p_world and t.y = p_y
$$;

create or replace function land_rock(p_world uuid, p_x int, p_y int) returns int language sql stable as $$
  select get_byte(t.rock, p_x) from land_tile t where t.world_id = p_world and t.y = p_y
$$;

create or replace function land_set_height(p_world uuid, p_x int, p_y int, p_v int) returns void language sql as $$
  update land_corner c set heights = b_put_i16(c.heights, p_x, greatest(-32768, least(32767, p_v)))
  where c.world_id = p_world and c.y = p_y
$$;

create or replace function land_set_dirt(p_world uuid, p_x int, p_y int, p_v int) returns void language sql as $$
  update land_corner c set dirt = set_byte(c.dirt, p_x, greatest(0, least(255, p_v)))
  where c.world_id = p_world and c.y = p_y
$$;

create or replace function land_set_tile(p_world uuid, p_x int, p_y int, p_v int) returns void language sql as $$
  update land_tile t set tiles = set_byte(t.tiles, p_x, greatest(0, least(255, p_v)))
  where t.world_id = p_world and t.y = p_y
$$;

create or replace function land_set_data(p_world uuid, p_x int, p_y int, p_v int) returns void language sql as $$
  update land_tile t set data = set_byte(t.data, p_x, greatest(0, least(255, p_v)))
  where t.world_id = p_world and t.y = p_y
$$;

create or replace function land_set_rock(p_world uuid, p_x int, p_y int, p_v int) returns void language sql as $$
  update land_tile t set rock = set_byte(t.rock, p_x, greatest(0, least(255, p_v)))
  where t.world_id = p_world and t.y = p_y
$$;

/**
 * Say that a tile changed, once, to everybody.
 *
 * Realtime carries the insert; a player who was away reads the same rows back
 * in order. One shout, two jobs, and no second code path for catching up.
 */
create or replace function land_announce(p_world uuid, p_x int, p_y int) returns void language sql as $$
  insert into tile_change (world_id, x, y, tile, data, corners)
  values (p_world, p_x, p_y, land_tile(p_world, p_x, p_y), land_data(p_world, p_x, p_y),
          array[land_height(p_world, p_x, p_y), land_height(p_world, p_x + 1, p_y),
                land_height(p_world, p_x + 1, p_y + 1), land_height(p_world, p_x, p_y + 1)])
$$;

/**
 * Lay down an empty island of a given size, flat and at sea level, ready to
 * have a real one written over it. Generating the island itself stays in the
 * browser: it is a big deterministic function of a seed, it already exists,
 * and there is nothing to be gained by teaching Postgres to do it again.
 */
create or replace function land_blank(p_world uuid, p_size int) returns void language plpgsql as $$
declare i int;
begin
  for i in 0..p_size loop
    insert into land_corner (world_id, y, heights, dirt)
    values (p_world, i, decode(repeat('00', (p_size + 1) * 2), 'hex'), decode(repeat('14', p_size + 1), 'hex'))
    on conflict do nothing;
  end loop;
  for i in 0..(p_size - 1) loop
    insert into land_tile (world_id, y, tiles, data, rock)
    values (p_world, i, decode(repeat('00', p_size), 'hex'), decode(repeat('00', p_size), 'hex'), decode(repeat('00', p_size), 'hex'))
    on conflict do nothing;
  end loop;
end $$;

-- ======================================================================
-- 20260914180300_defs.sql
-- ======================================================================

-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.

create table if not exists item_def (
  id text primary key, name text not null, category text not null, weight real not null,
  stackable boolean not null default false, decay real, charges int
);
create table if not exists tile_def (
  id int primary key, name text not null, speed real not null, blocks boolean not null default false,
  dig_yield text, mineable boolean not null default false, forage boolean not null default false,
  botanize boolean not null default false, pavable boolean not null default false,
  turns_to_dirt boolean not null default false, collect boolean not null default false
);
create table if not exists skill_def (
  id text primary key, name text not null, start real not null, parent text
);
create table if not exists material_def (
  id text primary key, difficulty real not null, weight real not null, wear real not null,
  decay real not null, edge real not null, soak real not null, bite real not null, hold real not null
);

truncate item_def, tile_def, skill_def, material_def;

insert into item_def values ('shovel', 'Shovel', 'tool', 3, false, null, null);
insert into item_def values ('pickaxe', 'Pickaxe', 'tool', 4, false, null, null);
insert into item_def values ('hatchet', 'Hatchet', 'tool', 2, false, null, null);
insert into item_def values ('carving_knife', 'Carving knife', 'tool', 0.5, false, null, null);
insert into item_def values ('chisel', 'Stone chisel', 'tool', 1, false, null, null);
insert into item_def values ('quern', 'Quern', 'tool', 9, false, null, null);
insert into item_def values ('whetstone', 'Whetstone', 'tool', 1.2, false, null, null);
insert into item_def values ('file', 'File', 'tool', 0.8, false, null, null);
insert into item_def values ('needle', 'Needle', 'tool', 0.05, false, null, null);
insert into item_def values ('awl', 'Awl', 'tool', 0.2, false, null, null);
insert into item_def values ('mallet', 'Mallet', 'tool', 1.5, false, null, null);
insert into item_def values ('trowel', 'Trowel', 'tool', 1, false, null, null);
insert into item_def values ('saw', 'Saw', 'tool', 1.5, false, null, null);
insert into item_def values ('rake', 'Rake', 'tool', 1.5, false, null, null);
insert into item_def values ('brush', 'Brush', 'tool', 0.6, false, null, null);
insert into item_def values ('sword', 'Sword', 'tool', 2, false, null, null);
insert into item_def values ('short_sword', 'Short sword', 'tool', 1.4, false, null, null);
insert into item_def values ('long_sword', 'Long sword', 'tool', 3, false, null, null);
insert into item_def values ('hunting_knife', 'Hunting knife', 'tool', 0.8, false, null, null);
insert into item_def values ('battle_axe', 'Battle axe', 'tool', 4, false, null, null);
insert into item_def values ('club', 'Club', 'tool', 2.5, false, null, null);
insert into item_def values ('maul', 'Maul', 'tool', 5, false, null, null);
insert into item_def values ('spear', 'Spear', 'tool', 2.2, false, null, null);
insert into item_def values ('short_bow', 'Short bow', 'tool', 1, false, null, null);
insert into item_def values ('medium_bow', 'Medium bow', 'tool', 1.4, false, null, null);
insert into item_def values ('long_bow', 'Long bow', 'tool', 1.8, false, null, null);
insert into item_def values ('helm', 'Helm', 'tool', 3, false, null, null);
insert into item_def values ('wool_cap', 'Wool cap', 'tool', 0.4, false, null, null);
insert into item_def values ('cloth_tunic', 'Cloth tunic', 'tool', 1.2, false, null, null);
insert into item_def values ('cloth_sleeves', 'Cloth sleeves', 'tool', 0.7, false, null, null);
insert into item_def values ('cloth_trousers', 'Cloth trousers', 'tool', 1, false, null, null);
insert into item_def values ('cloth_shoes', 'Cloth shoes', 'tool', 0.6, false, null, null);
insert into item_def values ('leather_cap', 'Leather cap', 'tool', 0.8, false, null, null);
insert into item_def values ('leather_jerkin', 'Leather jerkin', 'tool', 2.4, false, null, null);
insert into item_def values ('leather_sleeves', 'Leather sleeves', 'tool', 1.4, false, null, null);
insert into item_def values ('leather_trousers', 'Leather trousers', 'tool', 2, false, null, null);
insert into item_def values ('leather_boots', 'Leather boots', 'tool', 1.6, false, null, null);
insert into item_def values ('chain_coif', 'Chain coif', 'tool', 2.6, false, null, null);
insert into item_def values ('chain_hauberk', 'Chain hauberk', 'tool', 7.5, false, null, null);
insert into item_def values ('chain_sleeves', 'Chain sleeves', 'tool', 3.4, false, null, null);
insert into item_def values ('chain_leggings', 'Chain leggings', 'tool', 5, false, null, null);
insert into item_def values ('chain_boots', 'Chain boots', 'tool', 3, false, null, null);
insert into item_def values ('plate_breastplate', 'Breastplate', 'tool', 11, false, null, null);
insert into item_def values ('plate_arms', 'Plate arms', 'tool', 5, false, null, null);
insert into item_def values ('plate_legs', 'Plate legs', 'tool', 7.5, false, null, null);
insert into item_def values ('plate_boots', 'Plate boots', 'tool', 4.5, false, null, null);
insert into item_def values ('wooden_shield', 'Wooden shield', 'tool', 3.5, false, null, null);
insert into item_def values ('metal_shield', 'Metal shield', 'tool', 6, false, null, null);
insert into item_def values ('frying_pan', 'Frying pan', 'tool', 2, false, null, null);
insert into item_def values ('anvil', 'Anvil', 'misc', 60, false, 0.5, null);
insert into item_def values ('butchering_knife', 'Butchering knife', 'tool', 1, false, null, null);
insert into item_def values ('clay_bowl', 'Clay bowl', 'tool', 0.6, false, null, null);
insert into item_def values ('clay_pot', 'Clay pot', 'tool', 1.2, false, null, null);
insert into item_def values ('clay_jar', 'Clay jar', 'tool', 0.8, false, null, null);
insert into item_def values ('deed_stake', 'Deed stake', 'misc', 1, false, 4, null);
insert into item_def values ('crate_log', 'Log crate', 'misc', 30, false, 6, null);
insert into item_def values ('crate_plank', 'Plank crate', 'misc', 15, false, 6, null);
insert into item_def values ('water_skin', 'Water skin', 'misc', 0.5, false, null, 5);
insert into item_def values ('bucket', 'Bucket', 'tool', 1.6, false, 8, null);
insert into item_def values ('water_bucket', 'Bucket of water', 'tool', 6, false, 8, null);
insert into item_def values ('lye_bucket', 'Bucket of lye', 'tool', 6, false, 10, null);
insert into item_def values ('dirt', 'Dirt', 'material', 20, true, null, null);
insert into item_def values ('sand', 'Sand', 'material', 20, true, null, null);
insert into item_def values ('clay', 'Clay', 'material', 2, true, null, null);
insert into item_def values ('peat', 'Peat', 'material', 2, true, null, null);
insert into item_def values ('ash', 'Ashes', 'material', 0.3, true, 4, null);
insert into item_def values ('tar', 'Tar', 'material', 2, true, null, null);
insert into item_def values ('rock_shards', 'Rock shards', 'material', 20, true, 5, null);
insert into item_def values ('slate_shards', 'Slate shards', 'material', 20, true, 5, null);
insert into item_def values ('marble_shards', 'Marble shards', 'material', 20, true, 5, null);
insert into item_def values ('sandstone_shards', 'Sandstone shards', 'material', 20, true, 5, null);
insert into item_def values ('stone_brick', 'Stone brick', 'material', 15, true, 3, null);
insert into item_def values ('slate_brick', 'Slate brick', 'material', 15, true, 3, null);
insert into item_def values ('marble_brick', 'Marble brick', 'material', 15, true, 3, null);
insert into item_def values ('sandstone_brick', 'Sandstone brick', 'material', 15, true, 3, null);
insert into item_def values ('stone_slab', 'Stone slab', 'material', 18, true, 2, null);
insert into item_def values ('slate_slab', 'Slate slab', 'material', 18, true, 2, null);
insert into item_def values ('marble_slab', 'Marble slab', 'material', 18, true, 2, null);
insert into item_def values ('sandstone_slab', 'Sandstone slab', 'material', 18, true, 2, null);
insert into item_def values ('unfired_clay_brick', 'Unfired clay brick', 'material', 3, true, 12, null);
insert into item_def values ('unfired_clay_bowl', 'Unfired clay bowl', 'material', 0.7, true, 12, null);
insert into item_def values ('unfired_clay_pot', 'Unfired clay pot', 'material', 1.4, true, 12, null);
insert into item_def values ('unfired_clay_jar', 'Unfired clay jar', 'material', 0.9, true, 12, null);
insert into item_def values ('clay_brick', 'Clay brick', 'material', 3, true, 6, null);
insert into item_def values ('adobe', 'Adobe', 'material', 3, true, 10, null);
insert into item_def values ('mortar', 'Mortar', 'material', 2, true, 40, null);
insert into item_def values ('copper_ore', 'Copper ore', 'material', 2, true, 2, null);
insert into item_def values ('iron_ore', 'Iron ore', 'material', 2, true, 2, null);
insert into item_def values ('tin_ore', 'Tin ore', 'material', 2, true, 2, null);
insert into item_def values ('zinc_ore', 'Zinc ore', 'material', 2, true, 2, null);
insert into item_def values ('lead_ore', 'Lead ore', 'material', 2, true, 2, null);
insert into item_def values ('silver_ore', 'Silver ore', 'material', 2, true, 2, null);
insert into item_def values ('gold_ore', 'Gold ore', 'material', 2, true, 2, null);
insert into item_def values ('adamantine_ore', 'Adamantine ore', 'material', 2, true, 2, null);
insert into item_def values ('glimmersteel_ore', 'Glimmersteel ore', 'material', 2, true, 2, null);
insert into item_def values ('mithril_ore', 'Mithril ore', 'material', 2, true, 2, null);
insert into item_def values ('seryll_ore', 'Seryll ore', 'material', 2, true, 2, null);
insert into item_def values ('copper_lump', 'Copper lump', 'material', 1, true, 2, null);
insert into item_def values ('iron_lump', 'Iron lump', 'material', 1, true, 3, null);
insert into item_def values ('coal', 'Coal', 'material', 1, true, 3, null);
insert into item_def values ('tin_lump', 'Tin lump', 'material', 1, true, 2, null);
insert into item_def values ('zinc_lump', 'Zinc lump', 'material', 1, true, 2, null);
insert into item_def values ('lead_lump', 'Lead lump', 'material', 1.4, true, 1, null);
insert into item_def values ('silver_lump', 'Silver lump', 'material', 1, true, 1, null);
insert into item_def values ('gold_lump', 'Gold lump', 'material', 1, true, 1, null);
insert into item_def values ('adamantine_lump', 'Adamantine lump', 'material', 1, true, 0.5, null);
insert into item_def values ('glimmersteel_lump', 'Glimmersteel lump', 'material', 0.8, true, 0.5, null);
insert into item_def values ('mithril_lump', 'Mithril lump', 'material', 0.6, true, 0.5, null);
insert into item_def values ('seryll_lump', 'Seryll lump', 'material', 0.7, true, 0.5, null);
insert into item_def values ('bronze_lump', 'Bronze lump', 'material', 1, true, 1, null);
insert into item_def values ('steel_lump', 'Steel lump', 'material', 1, true, 1, null);
insert into item_def values ('brass_lump', 'Brass lump', 'material', 1, true, 1, null);
insert into item_def values ('pewter_lump', 'Pewter lump', 'material', 1, true, 1, null);
insert into item_def values ('electrum_lump', 'Electrum lump', 'material', 1, true, 1, null);
insert into item_def values ('anvil_mould', 'Anvil mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('nail_mould', 'Nail mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('pan_mould', 'Pan mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('rake_head_mould', 'Rake head mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('shovel_head_mould', 'Shovel head mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('hatchet_head_mould', 'Hatchet head mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('pickaxe_head_mould', 'Pickaxe head mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('knife_blade_mould', 'Knife blade mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('sword_blade_mould', 'Sword blade mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('helm_mould', 'Helm mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('axle_mould', 'Axle mould', 'tool', 1.4, false, 1, null);
insert into item_def values ('ribbon_mould', 'Ribbon mould', 'tool', 1.2, false, 1, null);
insert into item_def values ('nail', 'Nails', 'material', 0.01, true, 1, null);
insert into item_def values ('arrow', 'Arrows', 'material', 0.05, true, 3, null);
insert into item_def values ('arrow_head', 'Arrow heads', 'material', 0.02, true, 1, null);
insert into item_def values ('feather', 'Feathers', 'material', 0.01, true, 20, null);
insert into item_def values ('bow_string', 'Bowstring', 'material', 0.05, true, 8, null);
insert into item_def values ('yarn', 'Yarn', 'material', 0.15, true, 12, null);
insert into item_def values ('long_sword_blade', 'Long sword blade', 'material', 2, true, 1, null);
insert into item_def values ('short_sword_blade', 'Short sword blade', 'material', 1, true, 1, null);
insert into item_def values ('axe_head', 'Axe head', 'material', 2.6, true, 1, null);
insert into item_def values ('maul_head', 'Maul head', 'material', 3.4, true, 1, null);
insert into item_def values ('spear_head', 'Spear head', 'material', 1.2, true, 1, null);
insert into item_def values ('shield_boss', 'Shield boss', 'material', 2, true, 1, null);
insert into item_def values ('rake_head', 'Rake head', 'material', 1.2, true, 1, null);
insert into item_def values ('shovel_head', 'Shovel head', 'material', 1.2, true, 1, null);
insert into item_def values ('hatchet_head', 'Hatchet head', 'material', 1.2, true, 1, null);
insert into item_def values ('pickaxe_head', 'Pickaxe head', 'material', 1.2, true, 1, null);
insert into item_def values ('knife_blade', 'Knife blade', 'material', 1.2, true, 1, null);
insert into item_def values ('sword_blade', 'Sword blade', 'material', 1.2, true, 1, null);
insert into item_def values ('log', 'Log', 'material', 24, true, 18, null);
insert into item_def values ('plank', 'Plank', 'material', 2, true, 20, null);
insert into item_def values ('timber', 'Timber', 'material', 6, true, 18, null);
insert into item_def values ('wool', 'Wool', 'material', 0.4, true, 14, null);
insert into item_def values ('cloth', 'Cloth', 'material', 0.3, true, 14, null);
insert into item_def values ('fur', 'Fur', 'material', 1, true, 16, null);
insert into item_def values ('hide', 'Hide', 'material', 2, true, 40, null);
insert into item_def values ('leather', 'Leather', 'material', 1.5, true, 12, null);
insert into item_def values ('bone', 'Bone', 'material', 1, true, 8, null);
insert into item_def values ('gland', 'Gland', 'material', 0.2, true, 90, null);
insert into item_def values ('shaft', 'Shaft', 'material', 1, true, 20, null);
insert into item_def values ('ribbon', 'Metal ribbon', 'material', 0.4, true, 1, null);
insert into item_def values ('big_axle', 'Big axle', 'material', 8, true, 1, null);
insert into item_def values ('large_wheel', 'Large wheel', 'material', 12, true, 10, null);
insert into item_def values ('yoke', 'Yoke', 'material', 4, true, 10, null);
insert into item_def values ('milk_bucket', 'Bucket of milk', 'food', 6, false, 30, 5);
insert into item_def values ('cheese', 'Cheese', 'food', 0.4, true, 4, null);
insert into item_def values ('honey', 'Honey', 'food', 0.3, true, 0.4, null);
insert into item_def values ('wax', 'Beeswax', 'material', 0.2, true, 1, null);
insert into item_def values ('lantern', 'Lantern', 'tool', 1.4, false, 3, null);
insert into item_def values ('candle', 'Candle', 'misc', 0.2, true, 2, null);
insert into item_def values ('compost', 'Compost', 'material', 1.2, true, 2, null);
insert into item_def values ('saddle', 'Saddle', 'material', 7, true, 8, null);
insert into item_def values ('bridle', 'Bridle', 'material', 2, true, 8, null);
insert into item_def values ('thatch', 'Thatch', 'material', 0.5, true, 60, null);
insert into item_def values ('sprout', 'Sprout', 'plant', 0.1, true, 160, null);
insert into item_def values ('blueberry', 'Blueberries', 'food', 0.1, true, null, null);
insert into item_def values ('raspberry', 'Raspberries', 'food', 0.1, true, null, null);
insert into item_def values ('strawberry', 'Strawberries', 'food', 0.1, true, null, null);
insert into item_def values ('lingonberry', 'Lingonberries', 'food', 0.1, true, null, null);
insert into item_def values ('acorn', 'Acorn', 'food', 0.05, true, null, null);
insert into item_def values ('nuts', 'Nuts', 'food', 0.1, true, null, null);
insert into item_def values ('meat', 'Meat', 'food', 0.5, true, 160, null);
insert into item_def values ('cooked_meat', 'Cooked meat', 'food', 0.4, true, 90, null);
insert into item_def values ('baked_potato', 'Baked potato', 'food', 0.2, true, 90, null);
insert into item_def values ('roast_onion', 'Roast onion', 'food', 0.15, true, 90, null);
insert into item_def values ('roast_nuts', 'Roasted nuts', 'food', 0.1, true, 40, null);
insert into item_def values ('berry_compote', 'Berry compote', 'food', 0.3, true, 60, null);
insert into item_def values ('stew', 'Stew', 'food', 0.6, true, 70, null);
insert into item_def values ('pottage', 'Pottage', 'food', 0.7, true, 50, null);
insert into item_def values ('bread', 'Bread', 'food', 0.35, true, 70, null);
insert into item_def values ('porridge', 'Porridge', 'food', 0.4, true, 80, null);
insert into item_def values ('preserves', 'Preserves', 'food', 0.3, true, 12, null);
insert into item_def values ('flour', 'Flour', 'material', 0.1, true, 30, null);
insert into item_def values ('cornmeal', 'Cornmeal', 'material', 0.12, true, 30, null);
insert into item_def values ('dough', 'Dough', 'material', 0.3, true, 150, null);
insert into item_def values ('bandage', 'Bandage', 'misc', 0.05, true, 10, null);
insert into item_def values ('reed', 'Reed', 'material', 0.2, true, 60, null);
insert into item_def values ('papyrus', 'Papyrus', 'material', 0.05, true, 14, null);
insert into item_def values ('ink', 'Ink', 'material', 0.1, true, 8, null);
insert into item_def values ('book', 'Book', 'misc', 1.2, false, 6, null);
insert into item_def values ('fragment', 'Fragment', 'misc', 0.6, false, 3, null);
insert into item_def values ('statuette', 'Statuette', 'misc', 1.4, false, 2, null);
insert into item_def values ('old_lamp', 'Old lamp', 'misc', 0.9, false, 3, null);
insert into item_def values ('bronze_mirror', 'Bronze mirror', 'misc', 0.8, false, 3, null);
insert into item_def values ('bone_comb', 'Bone comb', 'misc', 0.15, false, 3, null);
insert into item_def values ('mixed_grass', 'Mixed grass', 'material', 0.1, true, 120, null);
insert into item_def values ('sage', 'Sage', 'plant', 0.05, true, null, null);
insert into item_def values ('basil', 'Basil', 'plant', 0.05, true, null, null);
insert into item_def values ('thyme', 'Thyme', 'plant', 0.05, true, null, null);
insert into item_def values ('mint', 'Mint', 'plant', 0.05, true, null, null);
insert into item_def values ('rosemary', 'Rosemary', 'plant', 0.05, true, null, null);
insert into item_def values ('onion_seed', 'Onion seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('carrot_seed', 'Carrot seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('cabbage_seed', 'Cabbage seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('potato_seed', 'Seed potatoes', 'plant', 0.1, true, 40, null);
insert into item_def values ('wheat_seed', 'Wheat seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('corn_seed', 'Corn seeds', 'plant', 0.03, true, 40, null);
insert into item_def values ('sage_seed', 'Sage seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('basil_seed', 'Basil seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('thyme_seed', 'Thyme seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('mint_seed', 'Mint seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('rosemary_seed', 'Rosemary seeds', 'plant', 0.02, true, 40, null);
insert into item_def values ('cotton_seed', 'Cotton seeds', 'plant', 0.05, true, 40, null);
insert into item_def values ('wemp_seed', 'Wemp seeds', 'plant', 0.05, true, 40, null);
insert into item_def values ('potato', 'Potato', 'food', 0.2, true, null, null);
insert into item_def values ('carrot', 'Carrot', 'food', 0.12, true, null, null);
insert into item_def values ('cabbage', 'Cabbage', 'food', 0.4, true, null, null);
insert into item_def values ('wheat', 'Wheat', 'food', 0.1, true, null, null);
insert into item_def values ('corn', 'Corn', 'food', 0.2, true, null, null);
insert into item_def values ('cotton', 'Cotton', 'material', 0.1, true, 30, null);
insert into item_def values ('wemp', 'Wemp fibre', 'material', 0.1, true, 30, null);
insert into item_def values ('toolbelt', 'Toolbelt', 'tool', 1.1, false, 3, null);
insert into item_def values ('rug', 'Rug', 'tool', 2.2, false, 6, null);
insert into item_def values ('composite_bow', 'Composite bow', 'tool', 2, false, null, null);
insert into item_def values ('scale_helm', 'Scale helm', 'tool', 1.6, false, null, null);
insert into item_def values ('scale_cuirass', 'Scale cuirass', 'tool', 5, false, null, null);
insert into item_def values ('scale_sleeves', 'Scale sleeves', 'tool', 3, false, null, null);
insert into item_def values ('scale_leggings', 'Scale leggings', 'tool', 4, false, null, null);
insert into item_def values ('scale_boots', 'Scale boots', 'tool', 2.4, false, null, null);
insert into item_def values ('tusk', 'Tusk', 'material', 1.6, true, 1, null);
insert into item_def values ('sinew', 'Sinew', 'material', 0.2, true, 4, null);
insert into item_def values ('dragon_scale', 'Dragon scale', 'material', 1.2, true, 0.2, null);
insert into item_def values ('worm', 'Worms', 'material', 0.05, true, 90, null);
insert into item_def values ('fishing_net', 'Fishing net', 'tool', 3.5, false, 5, null);
insert into item_def values ('creel', 'Creel', 'misc', 3, false, 4, null);
insert into item_def values ('snare', 'Snare', 'misc', 1.2, false, 5, null);
insert into item_def values ('deadfall', 'Deadfall', 'misc', 12, false, 4, null);
insert into item_def values ('cover', 'Healing cover', 'tool', 0.2, true, 12, null);
insert into item_def values ('dye', 'Dye', 'material', 0.8, true, 5, null);
insert into item_def values ('banner', 'Banner', 'misc', 4, false, 5, null);
insert into item_def values ('rope', 'Rope', 'material', 0.6, true, 6, null);
insert into item_def values ('thick_rope', 'Thick rope', 'material', 2.4, true, 4, null);
insert into item_def values ('onion', 'Onion', 'food', 0.15, true, null, null);
insert into item_def values ('corpse', 'Corpse', 'misc', 12, false, 90, null);
insert into item_def values ('stool', 'Stool', 'misc', 4, false, 4, null);
insert into item_def values ('sign', 'Sign', 'misc', 5, false, 5, null);
insert into item_def values ('great_sign', 'Signboard', 'misc', 11, false, 5, null);
insert into item_def values ('chair', 'Chair', 'misc', 7, false, 4, null);
insert into item_def values ('bench', 'Bench', 'misc', 12, false, 4, null);
insert into item_def values ('table', 'Table', 'misc', 18, false, 4, null);
insert into item_def values ('long_table', 'Long table', 'misc', 34, false, 4, null);
insert into item_def values ('desk', 'Writing desk', 'misc', 24, false, 4, null);
insert into item_def values ('bed', 'Bed', 'misc', 30, false, 5, null);
insert into item_def values ('cot', 'Cot', 'misc', 16, false, 5, null);
insert into item_def values ('chest', 'Chest', 'misc', 26, false, 4, null);
insert into item_def values ('coffer', 'Coffer', 'misc', 10, false, 4, null);
insert into item_def values ('cupboard', 'Cupboard', 'misc', 30, false, 4, null);
insert into item_def values ('wardrobe', 'Wardrobe', 'misc', 42, false, 4, null);
insert into item_def values ('shelves', 'Shelves', 'misc', 34, false, 4, null);
insert into item_def values ('bookshelf', 'Bookshelf', 'misc', 30, false, 4, null);
insert into item_def values ('larder', 'Larder', 'misc', 48, false, 4, null);
insert into item_def values ('barrel', 'Barrel', 'misc', 14, false, 4, null);
insert into item_def values ('lectern', 'Lectern', 'misc', 12, false, 4, null);
insert into item_def values ('coat_rack', 'Coat rack', 'misc', 6, false, 4, null);
insert into item_def values ('planter', 'Planter', 'misc', 12, false, 4, null);
insert into item_def values ('firewood_rack', 'Firewood rack', 'misc', 14, false, 4, null);
insert into item_def values ('ale_bucket', 'Bucket of ale', 'food', 6, false, 2, 5);
insert into item_def values ('cider_bucket', 'Bucket of cider', 'food', 6, false, 2, 5);
insert into item_def values ('mead_bucket', 'Bucket of mead', 'food', 6, false, 1.5, 5);
insert into item_def values ('wine_bucket', 'Bucket of wine', 'food', 6, false, 1, 5);
insert into item_def values ('fishing_rod', 'Fishing rod', 'tool', 1.4, false, 3, null);
insert into item_def values ('minnow', 'Minnow', 'food', 0.1, true, 9, null);
insert into item_def values ('perch', 'Perch', 'food', 0.5, true, 8, null);
insert into item_def values ('trout', 'Trout', 'food', 1.2, true, 8, null);
insert into item_def values ('pike', 'Pike', 'food', 3, true, 7, null);
insert into item_def values ('sturgeon', 'Sturgeon', 'food', 9, true, 6, null);
insert into item_def values ('cooked_fish', 'Cooked fish', 'food', 0.6, true, 4, null);
insert into item_def values ('apple', 'Apple', 'food', 0.2, true, 2, null);
insert into item_def values ('cherry', 'Cherry', 'food', 0.05, true, 5, null);
insert into item_def values ('olive', 'Olive', 'food', 0.06, true, 1.5, null);
insert into item_def values ('olive_oil', 'Olive oil', 'food', 0.4, true, 0.6, null);
insert into item_def values ('apple_pie', 'Apple pie', 'food', 0.9, true, 3, null);
insert into item_def values ('sack', 'Sack', 'misc', 0.4, false, 8, null);
insert into item_def values ('satchel', 'Satchel', 'misc', 1.2, false, 4, null);
insert into item_def values ('backpack', 'Backpack', 'misc', 2.4, false, 4, null);
insert into item_def values ('work_post', 'Work post', 'misc', 5, false, 4, null);
insert into item_def values ('hive', 'Hive', 'misc', 10, false, 4, null);
insert into item_def values ('rope_tool', 'Rope tool', 'tool', 1.2, false, null, null);
insert into item_def values ('spindle', 'Spindle', 'misc', 5, false, 4, null);
insert into item_def values ('loom', 'Loom', 'misc', 30, false, 4, null);
insert into item_def values ('smelter', 'Smelter', 'misc', 52, false, 3, null);
insert into item_def values ('kiln', 'Kiln', 'misc', 34, false, 3, null);
insert into item_def values ('oven', 'Oven', 'misc', 46, false, 3, null);
insert into item_def values ('well', 'Well', 'misc', 58, false, 3, null);
insert into item_def values ('bulk_bin', 'Bulk storage bin', 'misc', 38, false, 4, null);
insert into item_def values ('trash_crate', 'Trash crate', 'misc', 6, false, 4, null);
insert into item_def values ('cart', 'Small cart', 'misc', 26, false, 4, null);
insert into item_def values ('large_cart', 'Large cart', 'misc', 180, false, 4, null);
insert into item_def values ('wagon', 'Wagon', 'misc', 420, false, 4, null);
insert into item_def values ('rowing_boat', 'Rowing boat', 'misc', 210, false, 4, null);
insert into item_def values ('sailing_boat', 'Sailing boat', 'misc', 620, false, 4, null);
insert into item_def values ('small_barrel', 'Small barrel', 'misc', 7, false, 4, null);
insert into item_def values ('large_barrel', 'Large barrel', 'misc', 34, false, 4, null);
insert into tile_def values (0, 'Grass', 1, false, 'dirt', false, true, true, true, true, false);
insert into tile_def values (1, 'Dirt', 1, false, 'dirt', false, false, false, true, false, false);
insert into tile_def values (2, 'Packed dirt', 1.05, false, null, false, false, false, true, false, false);
insert into tile_def values (3, 'Sand', 0.9, false, 'sand', false, false, false, true, false, true);
insert into tile_def values (4, 'Rock', 0.9, false, null, true, false, false, false, false, false);
insert into tile_def values (5, 'Steppe', 1, false, 'dirt', false, true, true, true, true, false);
insert into tile_def values (6, 'Tundra', 0.95, false, 'dirt', false, true, true, true, true, false);
insert into tile_def values (7, 'Marsh', 0.6, false, 'dirt', false, true, true, false, true, false);
insert into tile_def values (8, 'Clay', 0.9, false, 'clay', false, false, false, false, false, true);
insert into tile_def values (9, 'Peat', 0.8, false, 'peat', false, false, false, false, false, true);
insert into tile_def values (10, 'Tar', 0.5, false, 'tar', false, false, false, false, false, true);
insert into tile_def values (11, 'Moss', 1, false, 'dirt', false, true, true, true, true, false);
insert into tile_def values (12, 'Snow', 0.8, false, null, true, false, false, false, false, false);
insert into tile_def values (13, 'Gravel', 1.15, false, null, false, false, false, true, false, false);
insert into tile_def values (14, 'Cobblestone', 1.25, false, null, false, false, false, false, false, false);
insert into tile_def values (15, 'Field', 0.9, false, 'dirt', false, false, false, false, true, false);
insert into tile_def values (16, 'Tree', 1, true, null, false, false, false, false, false, false);
insert into tile_def values (17, 'Bush', 0.5, false, null, false, false, false, false, false, false);
insert into tile_def values (18, 'Kelp', 1, false, null, false, false, false, false, false, false);
insert into tile_def values (19, 'Reed', 0.8, false, null, false, false, false, false, false, false);
insert into tile_def values (20, 'Lawn', 1, false, null, false, true, true, true, true, false);
insert into tile_def values (21, 'Stone slabs', 1.3, false, null, false, false, false, false, false, false);
insert into skill_def values ('body_strength', 'Body strength', 20, null);
insert into skill_def values ('body_stamina', 'Body stamina', 20, null);
insert into skill_def values ('body_control', 'Body control', 20, null);
insert into skill_def values ('mind_logic', 'Mind logic', 20, null);
insert into skill_def values ('soul_strength', 'Soul strength', 20, null);
insert into skill_def values ('digging', 'Digging', 1, null);
insert into skill_def values ('mining', 'Mining', 1, null);
insert into skill_def values ('prospecting', 'Prospecting', 1, null);
insert into skill_def values ('woodcutting', 'Woodcutting', 1, null);
insert into skill_def values ('forestry', 'Forestry', 1, null);
insert into skill_def values ('foraging', 'Foraging', 1, null);
insert into skill_def values ('botanizing', 'Botanizing', 1, null);
insert into skill_def values ('fishing', 'Fishing', 1, null);
insert into skill_def values ('brewing', 'Brewing', 1, null);
insert into skill_def values ('paving', 'Paving', 1, null);
insert into skill_def values ('masonry', 'Masonry', 1, null);
insert into skill_def values ('stonecutting', 'Stonecutting', 1, null);
insert into skill_def values ('carpentry', 'Carpentry', 1, null);
insert into skill_def values ('fine_carpentry', 'Fine carpentry', 1, null);
insert into skill_def values ('pottery', 'Pottery', 1, null);
insert into skill_def values ('tailoring', 'Tailoring', 1, null);
insert into skill_def values ('ropemaking', 'Ropemaking', 1, null);
insert into skill_def values ('cooking', 'Cooking', 1, null);
insert into skill_def values ('milling', 'Milling', 1, null);
insert into skill_def values ('smelting', 'Smelting', 1, null);
insert into skill_def values ('blacksmithing', 'Blacksmithing', 1, null);
insert into skill_def values ('weaponsmithing', 'Weaponsmithing', 1, null);
insert into skill_def values ('armorsmithing', 'Armoursmithing', 1, null);
insert into skill_def values ('farming', 'Farming', 1, null);
insert into skill_def values ('taming', 'Taming', 1, null);
insert into skill_def values ('animal_husbandry', 'Animal husbandry', 1, null);
insert into skill_def values ('butchering', 'Butchering', 1, null);
insert into skill_def values ('alchemy', 'Alchemy', 1, null);
insert into skill_def values ('prayer', 'Prayer', 1, null);
insert into skill_def values ('meditation', 'Meditation', 1, null);
insert into skill_def values ('repair', 'Repair', 1, null);
insert into skill_def values ('first_aid', 'First aid', 1, null);
insert into skill_def values ('papyrusmaking', 'Papyrusmaking', 1, null);
insert into skill_def values ('archaeology', 'Archaeology', 1, null);
insert into skill_def values ('restoration', 'Restoration', 1, null);
insert into skill_def values ('leatherworking', 'Leatherworking', 1, null);
insert into skill_def values ('chainsmithing', 'Chain armoursmithing', 1, null);
insert into skill_def values ('platesmithing', 'Plate armoursmithing', 1, null);
insert into skill_def values ('bowyery', 'Bowyery', 1, null);
insert into skill_def values ('fletching', 'Fletching', 1, null);
insert into skill_def values ('fighting', 'Fighting', 1, null);
insert into skill_def values ('swords', 'Swords', 1, null);
insert into skill_def values ('axes', 'Axes', 1, null);
insert into skill_def values ('mauls', 'Mauls', 1, null);
insert into skill_def values ('knives', 'Knives', 1, null);
insert into skill_def values ('polearms', 'Polearms', 1, null);
insert into skill_def values ('archery', 'Archery', 1, null);
insert into skill_def values ('shields', 'Shields', 1, null);
insert into skill_def values ('cloth_armour', 'Cloth armour', 1, null);
insert into skill_def values ('leather_armour', 'Leather armour', 1, null);
insert into skill_def values ('chain_armour', 'Chain armour', 1, null);
insert into skill_def values ('plate_armour', 'Plate armour', 1, null);
insert into skill_def values ('climbing', 'Climbing', 1, null);
insert into skill_def values ('swimming', 'Swimming', 1, null);
insert into material_def values ('0', -1, 0.88, 1.02, 1.05, 1, 0.96, 1.04, 1);
insert into material_def values ('1', -3, 0.8, 1.2, 1.25, 0.9, 0.88, 1.06, 0.95);
insert into material_def values ('2', 5, 1.22, 0.68, 0.85, 1.12, 1.16, 0.94, 1.12);
insert into material_def values ('3', 1, 1.05, 0.9, 1, 1.05, 1.02, 1, 1.05);
insert into material_def values ('4', -3, 0.78, 1.12, 1.12, 0.94, 0.9, 1.08, 0.95);
insert into material_def values ('5', 4, 0.9, 0.86, 0.35, 1, 1, 0.98, 1);
insert into material_def values ('6', 3, 1.18, 0.74, 0.95, 1.08, 1.1, 1.02, 1.06);
insert into material_def values ('7', 2, 1.02, 0.82, 0.9, 1.06, 1.06, 1.1, 1.04);
insert into material_def values ('8', 6, 1.3, 0.6, 0.55, 1.14, 1.2, 0.9, 1.08);
insert into material_def values ('9', 0, 1, 1, 1, 0.85, 0.9, 0.9, 1);
insert into material_def values ('10', 2, 1.1, 0.75, 1.35, 1.12, 1.12, 1.1, 1);
insert into material_def values ('11', -2, 0.85, 1.5, 1.1, 0.5, 0.55, 0.6, 1);
insert into material_def values ('12', -1, 0.9, 1.4, 1.05, 0.55, 0.6, 0.65, 1);
insert into material_def values ('13', -3, 1.95, 1.6, 0.7, 0.45, 0.72, 0.5, 1);
insert into material_def values ('14', 4, 1.2, 1.2, 0.45, 0.9, 0.86, 0.86, 1);
insert into material_def values ('15', 7, 2.1, 1.5, 0.15, 0.6, 0.75, 0.6, 1);
insert into material_def values ('16', 10, 0.75, 0.35, 0.15, 1.45, 1.25, 1.3, 1);
insert into material_def values ('17', 12, 0.6, 0.3, 0.1, 1.3, 1.48, 1.25, 1);
insert into material_def values ('18', 14, 0.42, 0.25, 0.08, 1.35, 1.4, 1.38, 1);
insert into material_def values ('19', 16, 0.7, 0.08, 0.02, 1.25, 1.36, 1.2, 1);
insert into material_def values ('20', 1, 1.05, 0.85, 0.8, 1.06, 1.06, 1.06, 1);
insert into material_def values ('21', 1, 1.05, 0.9, 0.72, 1, 1, 1, 1);
insert into material_def values ('22', -1, 1, 1.45, 0.9, 0.55, 0.6, 0.65, 1);
insert into material_def values ('23', 5, 1.5, 1.3, 0.25, 0.8, 0.86, 0.76, 1);
insert into material_def values ('24', 5, 1.05, 0.5, 0.95, 1.28, 1.22, 1.24, 1);

-- ======================================================================
-- 20260914180400_rules.sql
-- ======================================================================

-- The maths of doing something, ported from src/game/skills.ts and the roll
-- helpers in src/game/game.ts.
--
-- These are the algorithms, and they are the one thing that genuinely lives in
-- two places now. The constants do not: everything with a number in it comes
-- out of the generated def tables next door, so the only way these can drift
-- from the browser's copy is if somebody changes a formula, which is rare and
-- deliberate. The tests alongside check the two agree.

/** What is left of a gain at a given level: 1 at nothing, 0 at mastery. */
create or replace function skill_room(p_v double precision) returns double precision
  language sql immutable as $$ select power(greatest(0, 1 - p_v / 100), 1.8) $$;

/**
 * The least an honest go is worth. Without it the curve never quite arrives and
 * a hundred is a number nobody can reach.
 */
create or replace function min_gain() returns double precision
  language sql immutable as $$ select 0.0001::double precision $$;

/** One gain: the curve, floored, and then luck of a fifth either way. */
create or replace function skill_gain_of(p_v double precision, p_base double precision, p_roll double precision)
  returns double precision language sql immutable as
$$ select greatest(min_gain(), p_base * skill_room(p_v)) * p_roll $$;

/** Where a body is on a skill, falling back to where everybody starts. */
create or replace function skill_of(p_world uuid, p_uid uuid, p_id text) returns double precision
  language sql stable as
$$ select coalesce(
     (select s.value from skill s where s.world_id = p_world and s.uid = p_uid and s.id = p_id),
     (select d.start from skill_def d where d.id = p_id),
     1) $$;

/** Raise one, and say by how much. The roll happens here, where nobody can see it coming. */
create or replace function skill_raise(p_world uuid, p_uid uuid, p_id text, p_base double precision)
  returns double precision language plpgsql as $$
declare was double precision; now_v double precision;
begin
  was := skill_of(p_world, p_uid, p_id);
  now_v := least(100, was + skill_gain_of(was, p_base, 0.6 + 0.8 * random()));
  insert into skill (world_id, uid, id, value) values (p_world, p_uid, p_id, now_v)
    on conflict (world_id, uid, id) do update set value = excluded.value;
  return now_v - was;
end $$;

/**
 * Whether a go at something came off. Better skill and tools help, difficulty
 * hurts, and it is never certain either way: a third of the time at worst, all
 * but two in a hundred at best.
 *
 * The roll is here rather than in the browser, which is the whole point of the
 * move. A client that rolls its own successes is a client that never fails.
 */
create or replace function skill_check(p_skill double precision, p_difficulty double precision,
                                       p_tool_ql double precision default 0, p_ease double precision default 0)
  returns boolean language sql volatile as $$
  select random() < least(0.98, greatest(0.3,
    0.6 + (p_skill / 100) * 0.38 + p_tool_ql / 500
      - (case when p_ease > 0 then greatest(p_difficulty * 0.5, p_difficulty - p_ease) else p_difficulty end) / 150))
$$;

/**
 * What a piece of work comes out at. Your skill is the ceiling; the tool's
 * quality is the percentage chance of reaching it, and every other time the
 * thing comes out at 1, fit for nothing but being used up.
 */
create or replace function product_ql(p_skill double precision, p_tool_ql double precision default 0)
  returns double precision language sql volatile as $$
  select case
    when p_tool_ql <= 0 then least(100, greatest(1, least(100, greatest(1, p_skill)) * (0.6 + random() * 0.8) + 1))
    when random() * 100 < p_tool_ql then least(100, greatest(1, p_skill))
    else 1 end
$$;

create or replace function rarity_boost(p_rare text) returns double precision language sql immutable as $$
  select case p_rare when 'rare' then 1.1 when 'supreme' then 1.25 when 'fantastic' then 1.5 else 1 end
$$;

create or replace function rarity_keep(p_rare text) returns double precision language sql immutable as $$
  select case p_rare when 'rare' then 0.8 when 'supreme' then 0.6 when 'fantastic' then 0.35 else 1 end
$$;

/**
 * What a tool is worth at the work: its quality, bitten into by the state it
 * is in and lifted by its material, its rarity and any blessing on it. This
 * one figure decides how fast a job goes, how often it comes off, and how good
 * what comes out of it is.
 */
create or replace function tool_worth(p_ql real, p_dmg real, p_extra text, p_rare text, p_bless real)
  returns double precision language sql stable as $$
  select least(100,
      least(100, p_ql * coalesce((select m.bite from material_def m where m.id = p_extra), 1))
      * rarity_boost(p_rare)
      * (1 + least(3, coalesce(p_bless, 0)) * 0.09))
    * greatest(0.3, 1 - p_dmg / 160)
$$;

/** The best of a kind of tool in somebody's pack, and what it is worth. */
create or replace function tool_ql(p_world uuid, p_uid uuid, p_def text) returns double precision
  language sql stable as $$
  select coalesce(max(tool_worth(i.ql, i.dmg, i.extra, i.rare, i.bless)), 0)
  from item i
  where i.world_id = p_world and i.holder = 'player' and i.holder_uid = p_uid and i.def = p_def
$$;

/** How long a go at something takes: skill and a good tool both shorten it. */
create or replace function act_duration(p_base double precision, p_skill double precision,
                                        p_tool_ql double precision, p_control double precision default 1)
  returns double precision language sql immutable as $$
  select greatest(1.2, p_base * (1 - p_skill / 140) * (1 - p_tool_ql / 400) * p_control)
$$;

/** Steadiness of hand: body control makes every job a little quicker. */
create or replace function control_speed(p_world uuid, p_uid uuid) returns double precision
  language sql stable as $$ select greatest(0.6, 1 - (skill_of(p_world, p_uid, 'body_control') - 20) * 0.003) $$;

/**
 * Wear on a tool from one use. A poor tool goes to pieces far faster than a
 * good one, which is most of what quality is for. A tool worn through is gone.
 */
create or replace function wear_tool(p_item bigint, p_multiplier double precision default 1)
  returns void language plpgsql as $$
declare it item; amount double precision;
begin
  select * into it from item where id = p_item;
  if not found then return; end if;
  amount := (0.06 + 3 / (10 + it.ql)) * p_multiplier
            * coalesce((select m.wear from material_def m where m.id = it.extra), 1)
            * rarity_keep(it.rare);
  if it.dmg + amount >= 100 then
    delete from item where id = p_item;
  else
    update item set dmg = dmg + amount where id = p_item;
  end if;
end $$;

/** Tell somebody something. This is what the log line was, now it has to travel. */
create or replace function tell(p_world uuid, p_uid uuid, p_text text, p_kind text default 'event')
  returns void language sql as $$
  insert into event (world_id, uid, text, kind) values (p_world, p_uid, p_text, p_kind)
$$;

/**
 * What time it is on the island: seconds since it began, straight off the wall
 * clock. Nothing advances it and nothing can disagree about it — which is the
 * whole of what the old `clock` message and its drift-nudging were for.
 */
create or replace function world_time(p_world uuid) returns double precision language sql stable as $$
  select extract(epoch from (now() - w.epoch)) from world w where w.id = p_world
$$;

-- ======================================================================
-- 20260914180500_play.sql
-- ======================================================================

-- Joining an island, walking about it, and doing something to it.
--
-- ## Why nothing ticks
--
-- Supabase has no long-running process: an Edge Function answers a request and
-- stops, and there is nowhere to put a loop. That sounds like a problem for a
-- game with a clock in it, and it turns out to be a simplification.
--
-- Nothing here advances. A job that takes six seconds is written down once,
-- with the moment it will be finished, and then *settled* — the next time
-- anything touches that player, and by a slow sweep for anyone who has
-- wandered off mid-dig. The result is the same and there is no tick to miss,
-- no host tab to fall asleep, and no two machines that can disagree about
-- whether the hole got dug.

/**
 * Come ashore, or come back.
 *
 * The guest book is this table. Somebody the island has met keeps their body,
 * their skills and the spot they logged out on, because their row is still
 * here; somebody new gets a row on the shore with a starting kit. Which of the
 * two it is is not the client's to say — it is whether `auth.uid()` is already
 * in the table.
 */
create or replace function rpc_join(p_world uuid, p_name text)
  returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); w world; p player; born boolean := false;
begin
  if me is null then raise exception 'not signed in'; end if;
  select * into w from world where id = p_world;
  if not found then raise exception 'no such island'; end if;
  if not w.ready then raise exception 'that island is still being laid down'; end if;

  select * into p from player where world_id = p_world and uid = me;
  if not found then
    insert into player (world_id, uid, name, x, y, stats)
    values (p_world, me, coalesce(nullif(trim(p_name), ''), 'Wanderer'), w.spawn_x + 0.5, w.spawn_y + 0.5,
            '{"health":1,"stamina":1,"hunger":1,"thirst":1}'::jsonb)
    returning * into p;
    born := true;
    -- The kit everybody washes ashore with. Issued, so no one can better it
    -- into something it was never meant to be.
    insert into item (world_id, holder, holder_uid, def, ql, issued)
    select p_world, 'player', me, d, 20, true
    from unnest(array['hatchet','shovel','pickaxe','knife','mallet','trowel','saw','butchering_knife','rake']) d;
    perform tell(p_world, me, 'You wash ashore on an untouched island with a few tools and your wits.', 'system');
  else
    update player set seen_at = now(), name = coalesce(nullif(trim(p_name), ''), name)
      where world_id = p_world and uid = me returning * into p;
    perform tell(p_world, me, 'Your journey continues where you left off.', 'system');
  end if;

  return jsonb_build_object(
    'world', to_jsonb(w) - 'made_by',
    'you', to_jsonb(p),
    'new', born,
    'time', world_time(p_world));
end $$;

/**
 * Where I have walked to.
 *
 * The island believes a claim only as far as the clock allows: you may have
 * moved as far as the fastest thing on two legs could have carried you since
 * the last time you said so, plus a little slack for a link that stuttered.
 * It is not a movement simulation and is not meant to be — it is the ceiling
 * that stops a client putting itself on the far side of the island in order to
 * reach something it has no business reaching.
 */
create or replace function rpc_move(p_world uuid, p_x double precision, p_y double precision, p_level int default 0)
  returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); p player; w world; gap double precision; far double precision; allowed double precision;
begin
  if me is null then raise exception 'not signed in'; end if;
  perform settle(p_world, me);
  select * into p from player where world_id = p_world and uid = me for update;
  if not found then raise exception 'you are not on this island'; end if;
  select * into w from world where id = p_world;
  if p_x < 0 or p_y < 0 or p_x > w.size or p_y > w.size then raise exception 'that is off the island'; end if;

  gap := greatest(0.05, extract(epoch from (now() - p.moved_at)));
  far := sqrt(power(p_x - p.x, 2) + power(p_y - p.y, 2));
  -- 2.4 tiles a second is a walk; the rest is slack for a link that hiccups.
  allowed := 2.4 * least(gap, 10) * 1.6 + 1.5;
  if far > allowed then
    -- Not an error: a client that has been asleep is not a cheat, and telling
    -- it off would be unplayable. It is simply pulled back to where it could
    -- actually have got to, and it will notice and correct.
    p_x := p.x + (p_x - p.x) * (allowed / far);
    p_y := p.y + (p_y - p.y) * (allowed / far);
  end if;
  update player set x = p_x, y = p_y, level = p_level, moved_at = now(), seen_at = now()
    where world_id = p_world and uid = me;
  return jsonb_build_object('x', p_x, 'y', p_y, 'pulled', far > allowed);
end $$;

/**
 * Whether somebody standing where they are can work on what they have asked
 * for. Straight out of `Game.inRange`: a corner job wants you on one of the
 * four tiles that touch it, anything else wants you within its reach in the
 * square sense.
 */
create or replace function in_reach(p_px double precision, p_py double precision,
                                    p_target jsonb, p_corner boolean, p_range int)
  returns boolean language sql immutable as $$
  select case when p_corner then
      floor(p_px) between (p_target->>'cx')::int - 1 and (p_target->>'cx')::int
      and floor(p_py) between (p_target->>'cy')::int - 1 and (p_target->>'cy')::int
    else
      greatest(abs(floor(p_px) - (p_target->>'x')::int), abs(floor(p_py) - (p_target->>'y')::int)) <= coalesce(p_range, 1)
    end
$$;

-- ======================================================================
-- 20260914180600_act.sql
-- ======================================================================

-- Doing something to the island, decided entirely here.

create table if not exists action_def (
  id text primary key,
  label text not null,
  verb text not null,
  skill text,
  tool text,
  corner boolean not null default false,
  range int,
  stamina real not null default 0,
  base_time real not null,
  difficulty real not null default 10
);

insert into action_def (id, label, verb, skill, tool, corner, stamina, base_time, difficulty)
values ('dig', 'Dig', 'digging', 'digging', 'shovel', true, 0.05, 6, 8)
on conflict (id) do update set
  label = excluded.label, verb = excluded.verb, skill = excluded.skill, tool = excluded.tool,
  corner = excluded.corner, stamina = excluded.stamina, base_time = excluded.base_time,
  difficulty = excluded.difficulty;

/**
 * Whether a job may even be started: everything that can be known before the
 * work begins. The browser asks the same questions to grey out a menu item,
 * but its answer is a courtesy — this one is the answer.
 */
create or replace function act_refusal(p_world uuid, p_uid uuid, p_action text, p_target jsonb)
  returns text language plpgsql stable as $$
declare d action_def; p player; cx int; cy int; tx int; ty int; t tile_def;
begin
  select * into d from action_def where id = p_action;
  if not found then return 'There is no such thing as ' || p_action || '.'; end if;
  select * into p from player where world_id = p_world and uid = p_uid;
  if not found then return 'You are not on this island.'; end if;
  -- Deliberately not "are you busy": this is asked of the *next* go in a queue
  -- as well as the first, and by then the person asking is in the middle of
  -- exactly the job being asked about. Having it here meant a queue of six
  -- dug one hole and quietly stopped. Being busy is `rpc_act`'s business.
  if not in_reach(p.x, p.y, p_target, d.corner, d.range) then return 'You are too far away from that.'; end if;
  if d.tool is not null and tool_ql(p_world, p_uid, d.tool) <= 0 then
    return 'You need a ' || d.tool || ' to ' || lower(d.label) || '.';
  end if;

  if p_action = 'dig' then
    cx := (p_target->>'cx')::int; cy := (p_target->>'cy')::int;
    tx := (p_target->>'x')::int;  ty := (p_target->>'y')::int;
    select * into t from tile_def where id = land_tile(p_world, tx, ty);
    if t.dig_yield is null then return 'You cannot dig that.'; end if;
    if land_height(p_world, cx, cy) <= 0 then return 'You cannot dig below the water level.'; end if;
    if land_dirt(p_world, cx, cy) <= 0 then
      return 'That corner is bare rock. Only a pickaxe will take it lower.';
    end if;
  end if;
  return null;
end $$;

/**
 * Start something. The island writes down what was begun and when it will be
 * done, and that is all: no work happens now, and the outcome is not decided
 * now either. A client that hangs up halfway through still gets its hole.
 */
create or replace function rpc_act(p_world uuid, p_action text, p_target jsonb, p_times int default 1)
  returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); d action_def; why text; secs double precision; s double precision; tq double precision;
begin
  if me is null then raise exception 'not signed in'; end if;
  perform settle(p_world, me);
  if exists (select 1 from player where world_id = p_world and uid = me and act is not null) then
    perform tell(p_world, me, 'You are already busy.', 'error');
    return jsonb_build_object('started', false, 'why', 'You are already busy.');
  end if;
  why := act_refusal(p_world, me, p_action, p_target);
  if why is not null then
    perform tell(p_world, me, why, 'error');
    return jsonb_build_object('started', false, 'why', why);
  end if;
  select * into d from action_def where id = p_action;
  s := case when d.skill is null then 50 else skill_of(p_world, me, d.skill) end;
  tq := case when d.tool is null then 0 else tool_ql(p_world, me, d.tool) end;
  secs := act_duration(d.base_time, s, tq, control_speed(p_world, me));
  update player set
      act = p_action, act_target = p_target, act_started = now(),
      act_ends = now() + make_interval(secs => secs),
      act_left = greatest(1, least(100, coalesce(p_times, 1))), seen_at = now()
    where world_id = p_world and uid = me;
  perform tell(p_world, me, 'You start ' || d.verb || '.', 'info');
  return jsonb_build_object('started', true, 'ends', now() + make_interval(secs => secs), 'seconds', secs);
end $$;

/**
 * One go at a job, once its time has come. Everything that decides an outcome
 * — the roll, the quality, the skill gained — happens in here, on the server,
 * out of reach.
 */
create or replace function act_perform(p_world uuid, p_uid uuid, p_action text, p_target jsonb)
  returns void language plpgsql as $$
declare d action_def; tq double precision; s double precision; cx int; cy int; tx int; ty int;
        t tile_def; left_dirt int; made_ql double precision; yield text; gained double precision; tool_id bigint;
begin
  select * into d from action_def where id = p_action;
  s := case when d.skill is null then 50 else skill_of(p_world, p_uid, d.skill) end;
  tq := case when d.tool is null then 0 else tool_ql(p_world, p_uid, d.tool) end;

  if p_action = 'dig' then
    cx := (p_target->>'cx')::int; cy := (p_target->>'cy')::int;
    tx := (p_target->>'x')::int;  ty := (p_target->>'y')::int;
    select * into t from tile_def where id = land_tile(p_world, tx, ty);
    -- The tool wears whether or not the go came off, as it does in the hand.
    select i.id into tool_id from item i
      where i.world_id = p_world and i.holder = 'player' and i.holder_uid = p_uid and i.def = d.tool
      order by tool_worth(i.ql, i.dmg, i.extra, i.rare, i.bless) desc limit 1;
    if tool_id is not null then perform wear_tool(tool_id); end if;

    if not skill_check(s, d.difficulty, tq) then
      perform tell(p_world, p_uid, 'You fail to dig anything useful.', 'event');
      return;
    end if;
    perform land_set_height(p_world, cx, cy, land_height(p_world, cx, cy) - 1);
    left_dirt := land_dirt(p_world, cx, cy) - 1;
    perform land_set_dirt(p_world, cx, cy, left_dirt);
    if t.turns_to_dirt then perform land_set_tile(p_world, tx, ty, 1); end if;
    perform land_announce(p_world, tx, ty);
    if left_dirt <= 0 then
      perform tell(p_world, p_uid, 'Your shovel grates on bare rock.', 'event');
    end if;
    yield := coalesce(t.dig_yield, 'dirt');
    made_ql := product_ql(s, tq);
    insert into item (world_id, holder, holder_uid, def, ql) values (p_world, 'player', p_uid, yield, made_ql);
    gained := skill_raise(p_world, p_uid, d.skill, 1);
    perform tell(p_world, p_uid,
      'You dig up some ' || lower((select name from item_def where id = yield)) ||
      '. (QL ' || to_char(made_ql, 'FM990.0') || ')', 'event');
    if gained > 0 then
      perform tell(p_world, p_uid, 'Digging increased by ' || to_char(gained, 'FM0.0000') ||
        ' to ' || to_char(skill_of(p_world, p_uid, d.skill), 'FM990.0000') || '.', 'skill');
    end if;
  end if;
end $$;

/**
 * Finish whatever has come due.
 *
 * This is the whole of what replaces a running world. Every entry point calls
 * it first, so by the time anything reads a player that player is up to date;
 * and `rpc_sweep` calls it for people who walked away mid-job, so a hole does
 * not wait forever on somebody who has closed their laptop.
 *
 * It loops because a queue of six digs whose six seconds each went by while
 * nobody was looking is six digs that happened, not one.
 */
create or replace function settle(p_world uuid, p_uid uuid) returns int
  language plpgsql as $$
declare p player; d action_def; done int := 0; guard int := 0;
begin
  select * into p from player where world_id = p_world and uid = p_uid for update;
  if not found or p.act is null then return 0; end if;
  while p.act is not null and p.act_ends <= now() and guard < 200 loop
    guard := guard + 1;
    perform act_perform(p_world, p_uid, p.act, p.act_target);
    done := done + 1;
    select * into d from action_def where id = p.act;
    if p.act_left > 1 and act_refusal(p_world, p_uid, p.act, p.act_target) is null then
      -- Another go, starting when the last one ended rather than now: a queue
      -- settled late must not be paid for twice.
      update player set act_left = act_left - 1, act_started = p.act_ends,
             act_ends = p.act_ends + make_interval(secs => act_duration(
               d.base_time,
               case when d.skill is null then 50 else skill_of(p_world, p_uid, d.skill) end,
               case when d.tool is null then 0 else tool_ql(p_world, p_uid, d.tool) end,
               control_speed(p_world, p_uid)))
        where world_id = p_world and uid = p_uid returning * into p;
    else
      if p.act_left > 1 then
        perform tell(p_world, p_uid, 'You stop ' || d.verb || '.', 'info');
      end if;
      update player set act = null, act_target = null, act_started = null, act_ends = null, act_left = null
        where world_id = p_world and uid = p_uid returning * into p;
    end if;
  end loop;
  return done;
end $$;

/**
 * Settle everybody who has work owing, for a scheduled sweep. Nothing else
 * needs a timer: this is the one job that cannot wait on somebody coming back,
 * because they may not.
 */
create or replace function rpc_sweep() returns int language plpgsql security definer set search_path = public as $$
declare r record; n int := 0;
begin
  for r in select world_id, uid from player where act is not null and act_ends <= now() limit 500 loop
    n := n + settle(r.world_id, r.uid);
  end loop;
  return n;
end $$;

-- ======================================================================
-- 20260914180700_rls.sql
-- ======================================================================

-- Who may read what, and who may write anything at all.
--
-- The answer to the second is nobody. Every table below has row level security
-- on and not one write policy, so a client holding the publishable key can
-- select and nothing else. Changes happen only through the `rpc_` functions,
-- which run as their owner and so pass straight through these policies — which
-- is exactly what "Postgres enforces the rules" means in practice: the rules
-- are not a layer a client is asked to go through, they are the only door.

alter table world enable row level security;
alter table land_corner enable row level security;
alter table land_tile enable row level security;
alter table player enable row level security;
alter table skill enable row level security;
alter table item enable row level security;
alter table tile_change enable row level security;
alter table event enable row level security;

drop policy if exists world_read on world;
create policy world_read on world for select to authenticated using (true);

drop policy if exists land_corner_read on land_corner;
create policy land_corner_read on land_corner for select to authenticated using (true);
drop policy if exists land_tile_read on land_tile;
create policy land_tile_read on land_tile for select to authenticated using (true);
drop policy if exists tile_change_read on tile_change;
create policy tile_change_read on tile_change for select to authenticated using (true);

/** Everybody on an island you are on is visible to you; nobody else is. */
drop policy if exists player_read on player;
create policy player_read on player for select to authenticated using (
  exists (select 1 from player mine where mine.world_id = player.world_id and mine.uid = auth.uid())
);

/** What you have learned is yours. Reading it off somebody else is not a thing. */
drop policy if exists skill_read on skill;
create policy skill_read on skill for select to authenticated using (uid = auth.uid());

/** Your own pack, and anything lying on the ground where anyone could see it. */
drop policy if exists item_read on item;
create policy item_read on item for select to authenticated using (
  (holder = 'player' and holder_uid = auth.uid()) or holder = 'ground'
);

/** Lines meant for you, and lines meant for the whole island. */
drop policy if exists event_read on event;
create policy event_read on event for select to authenticated using (uid = auth.uid() or uid is null);

-- A real project already has this; a database built from these files alone
-- does not, and without it every select below fails as "relation does not
-- exist" — which is a confusing way to be told about a missing grant.
grant usage on schema public to anon, authenticated;

/**
 * The definition tables are the rulebook: readable by everyone, writable by
 * nobody. They get row level security like everything else — a `grant select`
 * is not a policy, and a table in an exposed schema with security switched off
 * is the thing every audit starts by pointing at, however harmless the rows.
 */
alter table item_def enable row level security;
alter table tile_def enable row level security;
alter table skill_def enable row level security;
alter table material_def enable row level security;
alter table action_def enable row level security;

drop policy if exists item_def_read on item_def;
create policy item_def_read on item_def for select to anon, authenticated using (true);
drop policy if exists tile_def_read on tile_def;
create policy tile_def_read on tile_def for select to anon, authenticated using (true);
drop policy if exists skill_def_read on skill_def;
create policy skill_def_read on skill_def for select to anon, authenticated using (true);
drop policy if exists material_def_read on material_def;
create policy material_def_read on material_def for select to anon, authenticated using (true);
drop policy if exists action_def_read on action_def;
create policy action_def_read on action_def for select to anon, authenticated using (true);

grant select on item_def, tile_def, skill_def, material_def, action_def to anon, authenticated;
grant select on world, land_corner, land_tile, player, skill, item, tile_change, event to authenticated;

-- ======================================================================
-- 20260914180800_found.sql
-- ======================================================================

-- Founding an island, and getting it down the wire in both directions.
--
-- Generating an island stays in the browser. It is a big deterministic
-- function of a seed, it already exists and is tested, and teaching Postgres
-- to do it again would be two islands that have to agree forever. So the
-- browser rolls one and hands it over, once, and after that the database owns
-- it and nobody may write to the land again except through the rules.
--
-- Bytes travel as base64 rather than as Postgres's own `\x` hex, which is
-- twice the size for no gain, and in batches of rows rather than one call per
-- row: a thousand-tile island is two thousand rows, and two thousand round
-- trips to found an island is a minute of watching a progress bar.

/** Start an island. It is not playable until the land has arrived. */
create or replace function rpc_found(p_name text, p_seed bigint, p_size int,
                                     p_spawn_x int, p_spawn_y int)
  returns uuid language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); w uuid;
begin
  if me is null then raise exception 'not signed in'; end if;
  if p_size < 8 or p_size > 4096 then raise exception 'that is not a size of island'; end if;
  insert into world (name, seed, size, spawn_x, spawn_y, ready, made_by)
  values (coalesce(nullif(trim(p_name), ''), 'An island'), p_seed, p_size, p_spawn_x, p_spawn_y, false, me)
  returning id into w;
  perform land_blank(w, p_size);
  return w;
end $$;

/**
 * Hand over a batch of the island's rows.
 *
 * Only whoever founded it, and only until it opens. The moment an island is
 * `ready` this refuses for good, which is the line that matters: after that
 * the only thing that can move a corner is a rule.
 */
create or replace function rpc_put_land(p_world uuid, p_rows jsonb)
  returns int language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); w world; r jsonb; n int := 0;
        h bytea; d bytea; ti bytea; da bytea; ro bytea;
begin
  if me is null then raise exception 'not signed in'; end if;
  select * into w from world where id = p_world;
  if not found then raise exception 'no such island'; end if;
  if w.made_by is distinct from me then raise exception 'that is not your island to lay down'; end if;
  if w.ready then raise exception 'that island is already open; the land is settled'; end if;

  for r in select * from jsonb_array_elements(p_rows) loop
    if (r->>'heights') is not null then
      h := decode(r->>'heights', 'base64');
      d := decode(r->>'dirt', 'base64');
      if length(h) <> (w.size + 1) * 2 or length(d) <> w.size + 1 then
        raise exception 'row % is the wrong width: % height bytes and % of soil, wanted % and %',
          r->>'y', length(h), length(d), (w.size + 1) * 2, w.size + 1;
      end if;
      update land_corner set heights = h, dirt = d
        where world_id = p_world and y = (r->>'y')::int;
    end if;
    if (r->>'tiles') is not null then
      ti := decode(r->>'tiles', 'base64');
      da := decode(r->>'data', 'base64');
      ro := decode(r->>'rock', 'base64');
      if length(ti) <> w.size or length(da) <> w.size or length(ro) <> w.size then
        raise exception 'row % is the wrong width: % tiles, wanted %', r->>'y', length(ti), w.size;
      end if;
      update land_tile set tiles = ti, data = da, rock = ro
        where world_id = p_world and y = (r->>'y')::int;
    end if;
    n := n + 1;
  end loop;
  return n;
end $$;

/** Open the island. One way: after this the land is only the rules' to change. */
create or replace function rpc_ready(p_world uuid)
  returns boolean language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); w world;
begin
  if me is null then raise exception 'not signed in'; end if;
  select * into w from world where id = p_world;
  if not found then raise exception 'no such island'; end if;
  if w.made_by is distinct from me then raise exception 'that is not your island to open'; end if;
  if (select count(*) from land_corner where world_id = p_world) <> w.size + 1
     or (select count(*) from land_tile where world_id = p_world) <> w.size then
    raise exception 'the land is not all here yet';
  end if;
  update world set ready = true where id = p_world;
  return true;
end $$;

/**
 * The island, back out again, a band of rows at a time.
 *
 * Reading the tables directly would work — the policies allow it — but
 * PostgREST hands `bytea` back as hex, which is twice the bytes for a thing
 * that is already the largest thing anybody downloads all day.
 */
create or replace function rpc_land(p_world uuid, p_y0 int, p_y1 int)
  returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not signed in'; end if;
  if p_y1 - p_y0 > 256 then raise exception 'ask for fewer rows at a time'; end if;
  return coalesce((
    select jsonb_agg(row ORDER BY y)
    from (
      select c.y,
             jsonb_build_object(
               'y', c.y,
               'heights', encode(c.heights, 'base64'),
               'dirt', encode(c.dirt, 'base64'),
               'tiles', encode(t.tiles, 'base64'),
               'data', encode(t.data, 'base64'),
               'rock', encode(t.rock, 'base64')) as row
      from land_corner c
      left join land_tile t on t.world_id = c.world_id and t.y = c.y
      where c.world_id = p_world and c.y between p_y0 and p_y1
    ) q), '[]'::jsonb);
end $$;

-- ======================================================================
-- 20260914185800_abandon.sql
-- ======================================================================

-- Giving an island up.
--
-- Wanted for two quite different reasons. A person who rolls an island by
-- accident, or with the wrong seed, should be able to throw it away rather
-- than leave it lying about forever. And the smoke test in CI raises a real
-- island on the real project every time it runs, which without this would
-- silt the database up a little more each commit.
--
-- Only whoever founded it, and everything on it goes: the cascades on
-- `world_id` see to the land, the people, the packs and the lines.

create or replace function rpc_abandon(p_world uuid)
  returns boolean language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); w world;
begin
  if me is null then raise exception 'not signed in'; end if;
  select * into w from world where id = p_world;
  if not found then return false; end if;
  if w.made_by is distinct from me then raise exception 'that is not your island to give up'; end if;
  delete from world where id = p_world;
  return true;
end $$;

-- ======================================================================
-- 20260914185900_doors.sql
-- ======================================================================

-- The lockdown, last of all.
--
-- This has to run after every function exists, which is why it is numbered to
-- sort to the end rather than living with the policies. It ran alongside them
-- once, and every function added in a later migration was published to the
-- world with nobody the wiser -- the loop can only take execute away from
-- functions that are there when it runs.

/**
 * Nothing but the front door.
 *
 * PostgREST publishes *every* function in this schema as an endpoint, so
 * without this a client could simply call `land_set_height` and put the island
 * wherever it liked. Execute is taken away from everybody and handed back only
 * to the handful of `rpc_` functions that check who is asking and what they
 * are asking for.
 */
do $$
declare f record;
begin
  for f in
    select p.oid::regprocedure as sig, p.proname
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
  loop
    execute format('revoke all on function %s from public, anon, authenticated', f.sig);
    if f.proname like 'rpc\_%' then
      execute format('grant execute on function %s to authenticated', f.sig);
    end if;
  end loop;
end $$;
