/**
 * Regions, biomes and exclusive materials.
 *
 * Every landmass on the chart is one region, matched to the nearest centre below;
 * the unnamed skerries take the region of the island they sit nearest. A region
 * decides three things: which biomes may appear on it, which rock and ores it
 * yields, and which tree species grow there. Materials listed on one region and
 * no other are exclusive to it by construction.
 *
 * Generated by Archipelago Forge.
 */
import { hash2 } from './noise';
import type { Atlas } from './atlas-world';

export const RockType = { Granite: 0, Slate: 1, Marble: 2, Sandstone: 3 } as const;
export type RockType = (typeof RockType)[keyof typeof RockType];

export const Ore = {
  None: 0, Iron: 1, Copper: 2, Tin: 3, Lead: 4, Zinc: 5, Adamantite: 6, Glimmersteel: 7, Seryll: 8,
} as const;
export type Ore = (typeof Ore)[keyof typeof Ore];

/** Tree species index. Cherry is new - add an entry to TREE_DEFS in tiles.ts: */
/*   { name: 'Cherry', shape: 'round', trunk: '#63452f', canopy: ['#f0b9cb', '#d98aa8', '#a85d7c'], size: 0.9, logs: 1 }, */
export const Species = { Birch: 0, Pine: 1, Oak: 2, Maple: 3, Willow: 4, Cedar: 5, Cherry: 6 } as const;

export interface Region {
  key: string;
  name: string;
  /** Measured centroid of the landmass on the chart, normalised 0..1. */
  at: [number, number];
  /** Shifts moisture on this region; negative is drier, which means steppe. */
  moistBias: number;
  /** Chance a dry tile becomes steppe rather than grass. */
  steppe: number;
  tundra: boolean;
  snow: boolean;
  rock: RockType;
  /** Weighted vein table. */
  ores: { ore: Ore; weight: number }[];
  /** Species that grow here and nowhere else. */
  trees: number[];
}

export const REGIONS: Region[] = [
  {
    key: 'Crescent',
    name: 'The Crescent',
    at: [0.5048, 0.7091],
    moistBias: -0.05,
    steppe: 0.35,
    tundra: false,
    snow: false,
    rock: RockType.Granite,
    ores: [{ ore: Ore.Iron, weight: 70 }, { ore: Ore.Copper, weight: 20 }, { ore: Ore.Tin, weight: 10 }],
    trees: [],
  },
  {
    key: 'NorthwestSteppe',
    name: 'Northwest Steppe',
    at: [0.2044, 0.2674],
    moistBias: -0.55,
    steppe: 1,
    tundra: false,
    snow: false,
    rock: RockType.Sandstone,
    ores: [{ ore: Ore.Iron, weight: 62 }, { ore: Ore.Lead, weight: 30 }, { ore: Ore.Adamantite, weight: 8 }],
    trees: [],
  },
  {
    key: 'NortheastTundra',
    name: 'Northeast Tundra',
    at: [0.8378, 0.2728],
    moistBias: -0.15,
    steppe: 0,
    tundra: true,
    snow: true,
    rock: RockType.Marble,
    ores: [{ ore: Ore.Iron, weight: 88 }, { ore: Ore.Glimmersteel, weight: 12 }],
    trees: [],
  },
  {
    key: 'Volcano',
    name: 'Volcano Isle',
    at: [0.5039, 0.1258],
    moistBias: 0,
    steppe: 0,
    tundra: false,
    snow: false,
    rock: RockType.Slate,
    ores: [{ ore: Ore.Iron, weight: 88 }, { ore: Ore.Seryll, weight: 12 }],
    trees: [],
  },
  {
    key: 'MiddleIsle',
    name: 'Middle Isle',
    at: [0.5043, 0.3946],
    moistBias: 0.05,
    steppe: 0,
    tundra: false,
    snow: false,
    rock: RockType.Granite,
    ores: [{ ore: Ore.Iron, weight: 60 }, { ore: Ore.Copper, weight: 22 }, { ore: Ore.Zinc, weight: 18 }],
    trees: [Species.Willow],
  },
  {
    key: 'EastIsle',
    name: 'East Isle',
    at: [0.7541, 0.4599],
    moistBias: 0.05,
    steppe: 0,
    tundra: false,
    snow: false,
    rock: RockType.Granite,
    ores: [{ ore: Ore.Iron, weight: 74 }, { ore: Ore.Copper, weight: 26 }],
    trees: [Species.Cherry],
  },
  {
    key: 'WestSkerry',
    name: 'West Skerry',
    at: [0.0801, 0.4309],
    moistBias: 0,
    steppe: 0,
    tundra: false,
    snow: false,
    rock: RockType.Granite,
    ores: [{ ore: Ore.Iron, weight: 100 }],
    trees: [],
  },
];

export const OCEAN_REGION = 255;
/** Centre of the crescent's inner bay, and the shore band players start on. */
export const BAY: [number, number] = [0.5221, 0.8193];
export const SPAWN_RADIUS = 0.15;
export const SPAWN_REGION = 0;

/**
 * One region per landmass, matched by centroid, then grown out over the water so
 * a coastal tile never falls outside a region.
 */
export function buildRegionMap(elev: Float32Array, n: number): Uint8Array {
  const comp = new Int32Array(n * n).fill(-1);
  const reg = new Uint8Array(n * n).fill(OCEAN_REGION);
  const centres: [number, number][] = [];
  for (let i = 0; i < n * n; i++) {
    if (elev[i] < 0 || comp[i] >= 0) continue;
    const me = centres.length;
    const st = [i];
    comp[i] = me;
    let area = 0;
    let sx = 0;
    let sy = 0;
    while (st.length) {
      const j = st.pop() as number;
      const x = j % n;
      const y = (j / n) | 0;
      area++; sx += x; sy += y;
      if (x > 0 && elev[j - 1] >= 0 && comp[j - 1] < 0) { comp[j - 1] = me; st.push(j - 1); }
      if (x < n - 1 && elev[j + 1] >= 0 && comp[j + 1] < 0) { comp[j + 1] = me; st.push(j + 1); }
      if (y > 0 && elev[j - n] >= 0 && comp[j - n] < 0) { comp[j - n] = me; st.push(j - n); }
      if (y < n - 1 && elev[j + n] >= 0 && comp[j + n] < 0) { comp[j + n] = me; st.push(j + n); }
    }
    centres.push([sx / area / n, sy / area / n]);
  }
  const pick = centres.map((c) => {
    let best = 0;
    let bestD = Infinity;
    REGIONS.forEach((R, q) => {
      const dx = c[0] - R.at[0];
      const dy = c[1] - R.at[1];
      if (dx * dx + dy * dy < bestD) { bestD = dx * dx + dy * dy; best = q; }
    });
    return best;
  });
  for (let i = 0; i < n * n; i++) if (comp[i] >= 0) reg[i] = pick[comp[i]];
  const q: number[] = [];
  for (let i = 0; i < n * n; i++) if (reg[i] !== OCEAN_REGION) q.push(i);
  for (let head = 0; head < q.length; head++) {
    const k = q[head];
    const x = k % n;
    const y = (k / n) | 0;
    if (x > 0 && reg[k - 1] === OCEAN_REGION) { reg[k - 1] = reg[k]; q.push(k - 1); }
    if (x < n - 1 && reg[k + 1] === OCEAN_REGION) { reg[k + 1] = reg[k]; q.push(k + 1); }
    if (y > 0 && reg[k - n] === OCEAN_REGION) { reg[k - n] = reg[k]; q.push(k - n); }
    if (y < n - 1 && reg[k + n] === OCEAN_REGION) { reg[k + n] = reg[k]; q.push(k + n); }
  }
  return reg;
}

export function regionAt(atlas: Atlas, x: number, y: number, size = 4096): number {
  const n = atlas.n;
  let ax = ((x / size) * n) | 0;
  let ay = ((y / size) * n) | 0;
  ax = ax < 0 ? 0 : ax > n - 1 ? n - 1 : ax;
  ay = ay < 0 ? 0 : ay > n - 1 ? n - 1 : ay;
  return atlas.region[ay * n + ax];
}

/** Species by climate, as in generate.ts: pines and cedars high, willows near water. */
export function pickSpecies(avgHeight: number, moisture: number, r: number): number {
  if (avgHeight > 95) return r < 0.6 ? Species.Pine : Species.Cedar;
  if (avgHeight < 7 && moisture > 0.1) return r < 0.7 ? Species.Willow : Species.Birch;
  if (r < 0.32) return Species.Birch;
  if (r < 0.6) return Species.Oak;
  if (r < 0.78) return Species.Maple;
  if (r < 0.9) return Species.Pine;
  return Species.Cedar;
}

/** Climate species, then the region filter: willow and cherry grow nowhere else. */
export function speciesFor(R: Region, avg: number, m: number, r: number): number {
  let sp = pickSpecies(avg, m, r);
  if (sp === Species.Willow && R.trees.indexOf(Species.Willow) < 0) sp = Species.Birch;
  if (R.trees.indexOf(Species.Cherry) >= 0 && r < 0.45) sp = Species.Cherry;
  return sp;
}

/**
 * Rock and ore under a tile. Veins are rolled per 8 x 8 tile cell, so a vein is
 * worth walking to rather than one lucky tile.
 */
export function resourceAt(seed: number, region: number, x: number, y: number): { rock: RockType; ore: Ore } {
  const R = REGIONS[region] || REGIONS[0];
  const cx = x >> 3;
  const cy = y >> 3;
  if (hash2(cx, cy, seed + 991) < 0.82) return { rock: R.rock, ore: Ore.None };
  let roll = hash2(cx, cy, seed + 4021) * R.ores.reduce((a, o) => a + o.weight, 0);
  for (const o of R.ores) {
    roll -= o.weight;
    if (roll <= 0) return { rock: R.rock, ore: o.ore };
  }
  return { rock: R.rock, ore: Ore.Iron };
}

let zoneCache: { atlas: Atlas; zone: number[] } | null = null;
/** Every beach texel on the inner bay: shore, beach height, inside the bay radius. */
function spawnZone(atlas: Atlas): number[] {
  if (zoneCache && zoneCache.atlas === atlas) return zoneCache.zone;
  const n = atlas.n;
  const e = atlas.elev;
  const zone: number[] = [];
  for (let y = 1; y < n - 1; y++) {
    for (let x = 1; x < n - 1; x++) {
      const i = y * n + x;
      if (e[i] < 0 || e[i] > 0.09 || atlas.region[i] !== SPAWN_REGION) continue;
      if (!(e[i - 1] < 0 || e[i + 1] < 0 || e[i - n] < 0 || e[i + n] < 0)) continue;
      const du = x / n - BAY[0];
      const dv = y / n - BAY[1];
      if (du * du + dv * dv > SPAWN_RADIUS * SPAWN_RADIUS) continue;
      zone.push(i);
    }
  }
  zoneCache = { atlas, zone };
  return zone;
}

/** A starting tile on the inner bay beach, chosen by seed. */
export function findBaySpawn(atlas: Atlas, seed: number, size = 4096): { x: number; y: number } {
  const zone = spawnZone(atlas);
  if (!zone.length) return { x: size >> 1, y: size >> 1 };
  const n = atlas.n;
  const i = zone[Math.floor(hash2(seed, 7, 13) * zone.length) % zone.length];
  return {
    x: Math.round(((i % n) + 0.5) / n * size),
    y: Math.round((((i / n) | 0) + 0.5) / n * size),
  };
}