/**
 * What changed in the generated definitions, and nothing else.
 *
 * Every `*_defs.sql` was a complete snapshot of the rulebook — truncate and
 * refill, four hundred kilobytes of it — written afresh whenever any one
 * number moved. Twenty-five of them came to **8.7 MB of the repository's 10**,
 * and every fresh database and every CI run replayed all twenty-five to arrive
 * at the last one.
 *
 * The snapshot is not the problem; keeping twenty-five is. So the snapshot
 * lives once, in `supabase/defs-state.sql`, outside `migrations/` where it can
 * be rewritten, and a migration carries the difference.
 *
 * ## What may safely be a difference
 *
 * Every statement in the dump is idempotent **except the inserts**, which only
 * mean anything after the truncate that clears the table — and the truncates
 * come in groups, because the tables have foreign keys between them and cannot
 * be cleared one at a time.
 *
 * So the rule is deliberately blunt: if the data statements are identical, the
 * migration carries only the statements that are new or changed — which is the
 * overwhelmingly common case, because what usually moves is a constant. If any
 * data statement differs at all, the migration is the whole snapshot, exactly
 * as before. A recipe really changing is worth four hundred kilobytes; a
 * number changing is worth four lines.
 */

/** Split generated SQL into statements, respecting dollar quoting. */
export function statements(sql) {
  const out = [];
  let buf = [];
  let tag = null;
  for (const line of sql.split('\n')) {
    buf.push(line);
    let rest = line;
    for (;;) {
      if (tag) {
        const end = rest.indexOf(tag);
        if (end < 0) break;
        rest = rest.slice(end + tag.length);
        tag = null;
      } else {
        const m = /\$[A-Za-z_]*\$/.exec(rest);
        if (!m) break;
        tag = m[0];
        rest = rest.slice(m.index + m[0].length);
      }
    }
    if (!tag && /;\s*$/.test(line)) {
      out.push(buf.join('\n'));
      buf = [];
    }
  }
  if (buf.join('\n').trim()) out.push(buf.join('\n'));
  return out;
}

const DATA = /^\s*(insert\s+into|update\s|truncate\s)/i;

/** The statements that only mean anything next to their truncate. */
export const dataOnly = (list) => list.filter((s) => DATA.test(s));

/**
 * The migration to write, given the last snapshot and the new one.
 *
 * Returns `{ sql, whole }` — `whole` says whether the data moved and the
 * snapshot had to go in entire.
 */
export function delta(oldSql, newSql) {
  const older = statements(oldSql);
  const newer = statements(newSql);
  const oldData = dataOnly(older).join('\n');
  const newData = dataOnly(newer).join('\n');
  if (oldData !== newData) return { sql: newSql, whole: true };

  const had = new Set(older);
  const changed = newer.filter((s) => !DATA.test(s) && !had.has(s));
  const head = [
    '-- Generated by scripts/dump-defs.ts from the TypeScript definitions.',
    '-- Do not edit: run `npm run defs` instead.',
    '--',
    '-- What changed since the last one. The rulebook itself did not move, so',
    '-- this is only the statements that did — every one of them idempotent, in',
    '-- the order the dump writes them. The whole snapshot lives in',
    '-- supabase/defs-state.sql.',
    '',
  ].join('\n');
  return { sql: `${head}${changed.join('\n')}\n`, whole: false, count: changed.length };
}
