/**
 * The definition tables, as SQL.
 *
 * With the rules in Postgres there are two places that need to know what a
 * shovel weighs and what grass yields. Writing them down twice is writing
 * them down wrong: one of the two drifts, and the one that drifts is whichever
 * you are not looking at.
 *
 * So the numbers keep living in TypeScript, where they always have, and this
 * turns them into rows. What Postgres holds is generated, never hand-edited —
 * the algorithms are ported, the constants are not.
 */
import { ITEM_DEFS } from '../src/game/items';
import { TILE_DEFS } from '../src/world/tiles';
import { SKILL_DEFS } from '../src/game/skills';
import { MATERIALS } from '../src/game/materials';

const q = (v: unknown): string => {
  if (v === undefined || v === null) return 'null';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replace(/'/g, "''")}'`;
};

const out: string[] = [];
out.push(`-- Generated by scripts/dump-defs.ts from the TypeScript definitions.`);
out.push(`-- Do not edit: run \`npm run defs\` instead.`);
out.push('');
out.push(`create table if not exists item_def (
  id text primary key, name text not null, category text not null, weight real not null,
  stackable boolean not null default false, decay real, charges int
);`);
out.push(`create table if not exists tile_def (
  id int primary key, name text not null, speed real not null, blocks boolean not null default false,
  dig_yield text, mineable boolean not null default false, forage boolean not null default false,
  botanize boolean not null default false, pavable boolean not null default false,
  turns_to_dirt boolean not null default false, collect boolean not null default false
);`);
out.push(`create table if not exists skill_def (
  id text primary key, name text not null, start real not null, parent text
);`);
out.push(`create table if not exists material_def (
  id text primary key, difficulty real not null, weight real not null, wear real not null,
  decay real not null, edge real not null, soak real not null, bite real not null, hold real not null
);`);
out.push('');
out.push('truncate item_def, tile_def, skill_def, material_def;');
out.push('');

for (const [id, d] of Object.entries(ITEM_DEFS)) {
  out.push(`insert into item_def values (${q(id)}, ${q(d.name)}, ${q(d.category)}, ${q(d.weight)}, ${q(!!d.stackable)}, ${q(d.decay)}, ${q(d.charges)});`);
}
for (const [id, d] of Object.entries(TILE_DEFS)) {
  out.push(`insert into tile_def values (${q(Number(id))}, ${q(d.name)}, ${q(d.speed)}, ${q(!!d.blocks)}, ${q(d.digYield)}, ${q(!!d.mineable)}, ${q(!!d.forage)}, ${q(!!d.botanize)}, ${q(!!d.pavable)}, ${q(!!d.turnsToDirt)}, ${q(!!d.collect)});`);
}
for (const d of SKILL_DEFS) {
  out.push(`insert into skill_def values (${q(d.id)}, ${q(d.name)}, ${q(d.start)}, ${q((d as { parent?: string }).parent)});`);
}
for (const [id, m] of Object.entries(MATERIALS)) {
  out.push(`insert into material_def values (${q(id)}, ${q(m.difficulty)}, ${q(m.weight)}, ${q(m.wear)}, ${q(m.decay)}, ${q(m.edge)}, ${q(m.soak)}, ${q(m.bite)}, ${q(m.hold)});`);
}
console.log(out.join('\n'));
