-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function pier_drop() returns int language sql immutable as $fn$ select 60::int $fn$;
create or replace function pier_water() returns int language sql immutable as $fn$ select 20::int $fn$;
create or replace function pier_clear() returns int language sql immutable as $fn$ select 5::int $fn$;
create or replace function pier_wall_drop() returns int language sql immutable as $fn$ select 100::int $fn$;
create or replace function pier_shoo() returns int language sql immutable as $fn$ select 8::int $fn$;
