-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function swim_depth() returns double precision language sql immutable as $fn$ select 4::double precision $fn$;
create or replace function swim_learn() returns double precision language sql immutable as $fn$ select 0.09::double precision $fn$;
create or replace function drown_warn() returns double precision language sql immutable as $fn$ select 4::double precision $fn$;
