-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function knack_chance(p_id text, p_base double precision) returns double precision language sql immutable as $fn$ select (case when p_id = any (array['swimming', 'climbing', 'driving', 'sailing']::text[]) then least(1, p_base / 1) else 1 end) / 5000::double precision $fn$;
