-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function fuel_value(p_item text) returns double precision language sql immutable as $fn$
  select case p_item
    when 'thatch' then 60
    when 'shaft' then 90
    when 'plank' then 120
    when 'peat' then 180
    when 'timber' then 240
    when 'log' then 600
    when 'coal' then 900
  end::double precision
$fn$;
create or replace function fuel_said() returns text language sql immutable as $fn$ select 'thatch, shafts, planks, peat, timbers, logs or coal' $fn$;
