-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function hunt_home() returns double precision language sql immutable as $fn$ select 40::double precision $fn$;
create or replace function wild_range() returns double precision language sql immutable as $fn$ select 28::double precision $fn$;
create or replace function herd_reach() returns double precision language sql immutable as $fn$ select 14::double precision $fn$;
