-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function change_keep() returns double precision language sql immutable as $fn$ select 3600::double precision $fn$;
create or replace function sweep_rows() returns double precision language sql immutable as $fn$ select 50000::double precision $fn$;
