-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function work_wind() returns double precision language sql immutable as $fn$ select 0.05::double precision $fn$;
create or replace function work_wind_spent() returns double precision language sql immutable as $fn$ select 0.6::double precision $fn$;
create or replace function work_hand() returns double precision language sql immutable as $fn$ select 0.05::double precision $fn$;
create or replace function night_eyes_from() returns double precision language sql immutable as $fn$ select 0.35::double precision $fn$;
create or replace function dark_swing() returns double precision language sql immutable as $fn$ select 0.5::double precision $fn$;
create or replace function dark_shot() returns double precision language sql immutable as $fn$ select 0.7::double precision $fn$;
create or replace function dark_hit() returns double precision language sql immutable as $fn$ select 0.8::double precision $fn$;
