-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function hunger_rate() returns double precision language sql immutable as $fn$ select 0.0004::double precision $fn$;
create or replace function thirst_rate() returns double precision language sql immutable as $fn$ select 0.0006::double precision $fn$;
create or replace function wind_rest() returns double precision language sql immutable as $fn$ select 0.05::double precision $fn$;
create or replace function wind_walk() returns double precision language sql immutable as $fn$ select 0.012::double precision $fn$;
create or replace function wind_per_level() returns double precision language sql immutable as $fn$ select 0.005::double precision $fn$;
create or replace function wind_starving() returns double precision language sql immutable as $fn$ select 0.3::double precision $fn$;
create or replace function heal_rate() returns double precision language sql immutable as $fn$ select 0.004::double precision $fn$;
create or replace function heal_fed() returns double precision language sql immutable as $fn$ select 0.2::double precision $fn$;
create or replace function swim_wind() returns double precision language sql immutable as $fn$ select 0.03::double precision $fn$;
create or replace function drown_rate() returns double precision language sql immutable as $fn$ select 0.05::double precision $fn$;
create or replace function exhausted() returns double precision language sql immutable as $fn$ select 0.08::double precision $fn$;
