-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function craft_head() returns double precision language sql immutable as $fn$ select 0.25::double precision $fn$;
create or replace function smith_gain() returns double precision language sql immutable as $fn$ select 0.5::double precision $fn$;
create or replace function brew_gain() returns double precision language sql immutable as $fn$ select 0.6::double precision $fn$;
create or replace function improve_gain() returns double precision language sql immutable as $fn$ select 0.4::double precision $fn$;
create or replace function restore_gain() returns double precision language sql immutable as $fn$ select 0.4::double precision $fn$;
create or replace function free_gain() returns double precision language sql immutable as $fn$ select 1.1::double precision $fn$;
create or replace function bandage_gain() returns double precision language sql immutable as $fn$ select 0.35::double precision $fn$;
create or replace function clean_gain() returns double precision language sql immutable as $fn$ select 0.8::double precision $fn$;
create or replace function tame_gain() returns double precision language sql immutable as $fn$ select 0.7::double precision $fn$;
create or replace function tame_nerve() returns double precision language sql immutable as $fn$ select 0.4::double precision $fn$;
create or replace function swing_fight() returns double precision language sql immutable as $fn$ select 0.3::double precision $fn$;
create or replace function swing_arm() returns double precision language sql immutable as $fn$ select 0.45::double precision $fn$;
create or replace function swing_body() returns double precision language sql immutable as $fn$ select 0.05::double precision $fn$;
create or replace function shot_fight() returns double precision language sql immutable as $fn$ select 0.2::double precision $fn$;
create or replace function shot_archery() returns double precision language sql immutable as $fn$ select 0.5::double precision $fn$;
create or replace function rod_gain() returns double precision language sql immutable as $fn$ select 0.4::double precision $fn$;
create or replace function net_gain() returns double precision language sql immutable as $fn$ select 0.55::double precision $fn$;
create or replace function breed_gain() returns double precision language sql immutable as $fn$ select 0.9::double precision $fn$;
