-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function grade_step(p_tier text) returns double precision language sql immutable as $fn$
  select case p_tier
    when 'common' then 1
    when 'rare' then 2.5
    when 'supreme' then 4.5
    when 'fantastic' then 7
  end::double precision
$fn$;
create or replace function board_top() returns int language sql immutable as $fn$ select 10::int $fn$;
