-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function stance_dealt(p_stance text) returns double precision language sql immutable as $fn$
  select coalesce(case p_stance
    when 'aggressive' then 1.2
    when 'balanced' then 1
    when 'defensive' then 0.8
  end, 1)::double precision
$fn$;
create or replace function stance_taken(p_stance text) returns double precision language sql immutable as $fn$
  select coalesce(case p_stance
    when 'aggressive' then 1.2
    when 'balanced' then 1
    when 'defensive' then 0.8
  end, 1)::double precision
$fn$;
create or replace function fight_back_still() returns double precision language sql immutable as $fn$ select 1.5::double precision $fn$;
create or replace function fight_leash() returns double precision language sql immutable as $fn$ select 8::double precision $fn$;
create or replace function fight_give_up() returns double precision language sql immutable as $fn$ select 6::double precision $fn$;
create or replace function blow_hunter() returns double precision language sql immutable as $fn$ select 1.4::double precision $fn$;
create or replace function blow_defensive() returns double precision language sql immutable as $fn$ select 2.5::double precision $fn$;
create or replace function blow_prey() returns double precision language sql immutable as $fn$ select 3.5::double precision $fn$;
create or replace function tired_at() returns double precision language sql immutable as $fn$ select 0.3::double precision $fn$;
create or replace function tired_slow() returns double precision language sql immutable as $fn$ select 0.6::double precision $fn$;
create or replace function swing_wind() returns double precision language sql immutable as $fn$ select 0.03::double precision $fn$;
create or replace function swing_wind_kg() returns double precision language sql immutable as $fn$ select 0.02::double precision $fn$;
