-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function max_step() returns double precision language sql immutable as $fn$ select 32::double precision $fn$;
create or replace function climb_learn_from() returns double precision language sql immutable as $fn$ select 0.3333333333333333::double precision $fn$;
create or replace function climb_learn() returns double precision language sql immutable as $fn$ select 0.04::double precision $fn$;
create or replace function climb_learn_steep() returns double precision language sql immutable as $fn$ select 0.12::double precision $fn$;
