-- Generated by scripts/dump-defs.ts from the TypeScript definitions.
-- Do not edit: run `npm run defs` instead.
--
-- What changed since the last one. The rulebook itself did not move, so
-- this is only the statements that did — every one of them idempotent, in
-- the order the dump writes them. The whole snapshot lives in
-- supabase/defs-state.sql.
create or replace function tick_seconds() returns double precision language sql immutable as $fn$ select 1::double precision $fn$;
create or replace function idle_logout() returns double precision language sql immutable as $fn$ select 450::double precision $fn$;
create or replace function calls_a_minute() returns double precision language sql immutable as $fn$ select 480::double precision $fn$;
